web-platform-dx/web-features

- 2022-backgrounder.md
- README.md
The background quickly summarizes the starting and explorations done so far, linking to documents and slides developed along the way.
> Add backgrounder on interoperable features exploration

- .github/workflows/pull_request.yml
- package.json
- packages/web-features/README.md
- packages/web-features/package.json
- scripts/build.ts
It needs its own package.json and README. Even if they can be derived by
scripts, it's still convenient to use this structure. It's similar to
webref, and also the structure that Lerna expects. But it's also
possible to just run `npm publish` from the subdirectory.
> Define built web-features package in its own directory

- docs/readme.md
This is to give form to some of the things we've discussed so far in https://github.com/web-platform-dx/feature-set/issues/24 and https://github.com/web-platform-dx/feature-set/issues/23.
I don't expect this to be the last word on the subject, as we create more feature descriptions and understand how they all fit together.
> Add initial docs with naming conventions

- feature-group-definitions/webvtt.yml
VTTCue is for any VTTCue creation, whether from the JS constructor or
the WebVTT parser.
VTTCueParser is for the creation of a WebVTT parser for a `<track>`
element.
VTTCueRender is for when a cue is actually displayed, which would be
on top of a playing `<video>`.
> Add use counters for WebVTT

- feature-group-definitions/masonry.yml
- feature-group-definitions/subgrid.yml
This is a follow up to https://github.com/web-platform-dx/feature-set/pull/78. It adds a group for `masonry` and adds compat data for both it and `subgrid`.
A natural follow up to this would be to introduce a structured way of describing the relationship between these features (i.e., that "classical" grid, subgrid, and masonry are each members of a common omnibus grid group).
cc: @captainbrosset
> Add compat features for masonry and subgrid

- packages/web-features/package.json
This PR bumps the version number for `web-features` in anticipation of a release. @foolip I think you're the one with permissions to publish, so you'll need to do this.
1. Review the JSON diff, below, as well as the regular GitHub diff UI. It shouldn't be too surprising, but look out for:
- New features, specs, and usage stats
- The extremely speculative "baseline" data in a couple of features
3. If it's satisfactory, merge. Make sure to complete the remaining steps before merging any subsequent PRs.
5. Locally, make sure you have a clean working directory (e.g., run `git stash` and `git restore --staged --worktree`).
6. From the root of the repository, run these commands to publish:
```shell
$ git checkout main
$ git pull origin main # assuming that `origin` is something like …
```
> Bump web-features to v0.2.0

- feature-group-definitions/popover.yml
This is the use counter given by the implementer:
https://groups.google.com/a/chromium.org/g/blink-dev/c/uB_jxbRmjAM/m/552qSSNHAQAJ
> Link to main popover use counter

- feature-group-definitions/webvtt.yml
- package-lock.json
- package.json
`npm test` was _applying_ the formatter, not checking whether prettier was satisfied. This PR fixes the mistake and applies YAML formatting to the one file currently out of compliance.
> Fix formatting test

- scripts/release.ts
If you haven't recently logged into npm, then publishing fails. This checks ahead of time, so you don't push a tag and fail to publish.
I just published v0.2.1 and ran into this little hiccup with npm authorization. This makes it easier to recover from a very likely issue.
> Make it easier to diagnose publishing permissions

- index.ts
This passe the BCD keys to the published package. Requested by @LeoMcA.
> Expose `compat_features` to consumers

- feature-group-definitions/custom-elements.yml
- scripts/specs.ts
This changes the spec test to allow spec URL tests to pass when:
- A spec URL ~~starts with a URL~~ is known to `web-specs` (i.e., is one of `web-specs` `url` or `pages` strings, excluding hash fragments)
- A spec URL is specifically allowlisted
Merging this will unblock https://github.com/web-platform-dx/feature-set/pull/116.
> Allow more permissive spec URLs

- feature-group-definitions/array-at.yml
- feature-group-definitions/array-flat.yml
- feature-group-definitions/class-syntax.yml
Now that we've got better spec URL validation, we can uncomment some URLs that would have previously failed.
> Use more specific spec URLs

- feature-group-definitions/flexbox.yml
This adds features and simplified support status to `flexbox`. This is probably the first great example of messy data creating issues.
Some issues I encountered here:
- I skimmed through the flexbox spec and wrote a list of expected BCD features. I commented out the ones that don't exist in BCD. It's interesting to see what keys do and do not exist in BCD. The two exceptions I deleted outright were `css.properties.flex-basis.content` and `css.properties.flex-basis.fit-content`, which seem to be distinctly later additions. It's interesting to consider whether we ought to complete the "missing" subfeatures, or to do as BCD does: assume they're supported with the parent feature.
- The `{flex,grid}_context` pseudo-groups in BCD are quite challenging to deal with. I once opened …
> Add flexbox compat features and status

- packages/web-features/README.md
@foolip You suggested this last week, to make explicit what we intend with the current schema.
(It's likely that we'll want to switch browsers to booleans or something, but it seems ill-advised to change the schema _now_, before we've received feedback from our first consumers.)
> Document baseline indication with data from `web-features`

- .gitignore
- packages/web-features/README.md
- packages/web-features/index.ts
- packages/web-features/package-lock.json
- packages/web-features/package.json
- packages/web-features/tsconfig.json
This converts the `web-features` package into a regularly `import`-able module. Some consequences of the way I've done this:
- I don't know how to publish TS types today, but I assume that's something we might have an interest in later, so I made sure that the module is TypeScript from the start. This requires a little bit of new configuration (in the `package.json` and the addition of a `tsconfig.json`) to prevent `tsc` from spewing `.js` files everywhere.
- The package has two exports: `index.js` and `index.json`. By doing it this way, `import features from "web-features/index.json" assert { type: "json" }` is still possible. This also opens the door for additional exports (e.g., including the schema alongside the data).
If you wish to test this package locally:
1. Check out this …
> Allow package to be imported without type assertion

- feature-group-definitions/offscreen-canvas.yml
We don't have baseline display assets or guidelines for "coming soon" features, so this hides the status until we've sorted that out. This is similar to the way we've handled `container-queries` and `grid-animation`.
> `offscreen-canvas`: suppress baseline status (for now)

- .github/dependabot.yml
- package-lock.json
- package.json
This PR:
* Aligns `@types/node` and `package.json` with `.node-version`
* Tells Dependabot to stop upgrade `@types/node` by major version
Closes https://github.com/web-platform-dx/feature-set/pull/170.
> Downgrade `@types/node` to match `.node-version` Node.js

- README.md
The README linked to the charter of the WebDX Community Group, but the charter is a bit of a dead-end for people who would like to get involved. This update rather targets the official [WebDX Community Group home page](https://www.w3.org/community/webdx/), which now features a "Work mode" blog post to clarify workstreams, meetings and communication channels.
> Adjust README links to WebDX Community Group

- feature-group-definitions/navigation.yml
- scripts/specs.ts
https://github.com/whatwg/html/pull/8502 merged a few weeks ago, so we can now point to the real spec instead of the page linking the work-in-progress pull request.
> Update Navigation API URL (and remove exception)

- feature-group-definitions/scrollintoview.yml
Corresponds to https://caniuse.com/scrollintoview
- Is this a recognizable web feature to web developers? (caniuse features are often made by request, so it's likely, but let's double check our work here.)
> Add `Element.scrollIntoView()` feature

- feature-group-definitions/viewport-relative-unit-variants.yml
- feature-group-definitions/viewport-relative-units.yml
Here's a fun one that tests the limits of the schema: viewport relative units, such as `vw`, `lvw`, `svw`, `dvw`, and friends.
Some thoughts on this one:
- I nearly made (and still might have) two separate groups here: one for (most of) the older user-agent default viewport lengths and one for the newer small, large, and dynamic lengths. I opted for one group for a bunch little reasons:
- a weird gap in the spec and support for the original units (`vi`), which was only resolved at the introduction of the new units
- a want for a good name for the new units
- my own (mostly-incorrect) understanding that the original units _weren't_ widely supported until recently
Taken together, I made an editorial decision that viewport-relative units weren't really "done" until recently and could be …
> Add `viewport-relative-units`

- feature-group-definitions/tabindex.yml
Corresponds to https://caniuse.com/tabindex-attr
> Add `tabindex` global attribute feature

- feature-group-definitions/read-write-pseudo-classes.yml
Corresponds to https://caniuse.com/css-read-only-write
> Add `:read-write` and `:read-only` pseudo-classes

- feature-group-definitions/font-variant-alternates.yml
Corresponds to https://caniuse.com/font-variant-alternates
I think caniuse might be slightly wrong about the support story here. It doesn't call out some [differences in Safari noted by BCD](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#browser_compatibility). Another one that may require work when we generate statuses.
<details>
<summary>This is a new feature. Expand for ideas for reviewing it.</summary>
- Is this a recognizable web feature to web developers? (caniuse features are often made by request, so it's likely, but let's double check our work here.)
- Are the …
> Add `font-variant-alternates` feature

- feature-group-definitions/svg2-script-html-equivalance.yml
This captures the requirement for SVG `<script>` elements to operate equivalently to HTML's `<script>` elements, including `async`, `defer`, and `module`.
I borrowed from the spec to name it, so I don't know if it's a good name. `async-deferable-modular-scripts-in-svg` felt like a mouthful.
cc: @bsmth, @Elchi3 
See also: https://github.com/mdn/browser-compat-data/pull/20502/
> Create `svg2-script-html-equivalance` feature

- feature-group-definitions/media-capture.yml
This corresponds to https://caniuse.com/html-media-capture.
> Add HTML media capture feature

- feature-group-definitions/is.yml
Corresponds to https://caniuse.com/css-matches-pseudo
> Add `:is()` pseudo-class feature

- feature-group-definitions/set-methods.yml
https://github.com/tc39/proposal-set-methods
Thoughts I had while creating this PR:
- Should I sort the `compat_feature` list alphabetically?
- It's all flat in one folder... Should this be in a javascript folder? hm, but there will be groups that will have features from various technologies, so maybe should it be categorized in some other way? In a 2023 folder? Maybe we don't need folders for now...
> Add Set methods group

- GOVERNANCE.md
On Tuesday, 7 November 2023, the governance team decided to invite Alexis to the owners group, as the maintainer of a key consumer of web-features data, _Can I use…?_.
@Fyrd would you confirm acceptance of the invitation? Thank you!
> Add @Fyrd as an owner

- scripts/caniuse.ts
~~The build will fail on this PR because `@types/caniuse-lite`'s type definitions are out of date. See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67330.~~ I've temporarily overridden the type so we can move on with this.
This PR checks that features' `caniuse` values point only to features that appear on caniuse.com. It disallows caniuse ID where the caniuse `shown` property is `false`.
This impacts the caniuse burndown list. I've chosen to mark them as complete, but also to note that they're hidden features.
This PR closes #275.
> Reject hidden caniuse features

- feature-group-definitions/text-indent.yml
Corresponds to https://caniuse.com/css-text-indent
> Add `text-indent` feature

- feature-group-definitions/default.yml
Corresponding to https://caniuse.com/css-default-pseudo
> Add `:default` pseudo class feature

- feature-group-definitions/content-visibility.yml
- Are listed features plausible parts pieces of the feature as a whole?
> `content-visibility`: add compat features

- feature-group-definitions/indeterminate.yml
Corresponds to https://caniuse.com/css-indeterminate-pseudo
> Add `:indeterminate` pseudo class feature

- feature-group-definitions/overflow-shorthand.yml
This corresponds to https://caniuse.com/css-overflow
> Add `overflow` shorthand feature (with `clip` values)

- feature-group-definitions/input-event.yml
Corresponds to https://caniuse.com/input-event
- Is this a recognizable web feature to web developers? (caniuse features are often made by request, so it's likely, but let's double check our work here.)
> Add `input` event feature

- feature-group-definitions/async-await.yml
| Key                                             | Baseline | Since      | Versions                                                                                                                    |
| :---------------------------------------------- | :------: | :--------- | --------------------------------------------------------------------------------------------------------------------------- |
| **async-await**                                 |     ✅    | 2017-04-05 | Chrome 55<br>Chrome Android 55<br>Edge 15 🔑💎<br>Firefox 52<br>Firefox for Android 52<br>Safari 10.1<br>Safari on iOS 10.3 |
| javascript.builtins.AsyncFunction               |     ✅    | 2017-04-05 | Chrome 55<br>Chrome Android 55<br>Edge 15 🔑💎<br>Firefox 52<br>Firefox for Android 52<br>Safari 10.1<br>Safari on iOS …
> `async-await`: set Baseline status

- feature-group-definitions/async-clipboard.yml
| Key                                       | Baseline | Since      | Versions                                                                                                                    |
| :---------------------------------------- | :------: | :--------- | --------------------------------------------------------------------------------------------------------------------------- |
| **async-clipboard**                       |     ❌    |            | Chrome ❌<br>Chrome Android ❌<br>Edge ❌<br>Firefox ❌<br>Firefox for Android ❌<br>Safari ❌<br>Safari on iOS ❌                 |
| api.Clipboard                             |     ✅    | 2020-03-24 | Chrome 66<br>Chrome Android 66<br>Edge 79<br>Firefox 63<br>Firefox for Android 63<br>Safari 13.1 🔑💎<br>Safari on iOS 13.4 |
| …
> `async-clipboard`: set Baseline status

- feature-group-definitions/background-fetch.yml
- feature-group-definitions/bigint.yml
- feature-group-definitions/broadcast-channel.yml
| Key                                                           | Baseline | Since | Versions                                                                                                       |
| :------------------------------------------------------------ | :------: | :---- | -------------------------------------------------------------------------------------------------------------- |
| **background-fetch**                                          |     ❌    |       | Chrome 74<br>Chrome Android 74<br>Edge 79<br>Firefox ❌<br>Firefox for Android ❌<br>Safari ❌<br>Safari on iOS ❌ |
| api.BackgroundFetchEvent                                      |     ❌    |       | Chrome 74<br>Chrome Android 74<br>Edge 79<br>Firefox ❌<br>Firefox for Android ❌<br>Safari ❌<br>Safari on iOS ❌ |
| …
> `b*` features: set Baseline status

- feature-group-definitions/class-syntax.yml
- feature-group-definitions/constraint-validation.yml
- feature-group-definitions/content-visibility.yml
- feature-group-definitions/custom-elements.yml
- feature-group-definitions/custom-properties.yml
| Key                            | Baseline | Since      | Versions                                                                                                                    |
| :----------------------------- | :------: | :--------- | --------------------------------------------------------------------------------------------------------------------------- |
| **class-syntax**               |     ✅    | 2017-03-27 | Chrome 42<br>Chrome Android 42<br>Edge 13<br>Firefox 45<br>Firefox for Android 45<br>Safari 10.1 🔑💎<br>Safari on iOS 10.3 |
| javascript.classes             |     ✅    | 2016-03-08 | Chrome 42<br>Chrome Android 42<br>Edge 13<br>Firefox 45 🔑💎<br>Firefox for Android 45<br>Safari 9<br>Safari on iOS 9       |
| javascript.classes.constructor |     ✅    | 2016-03-08 | …
> `c*` features: set Baseline status (and correct feature list)

- packages/web-features/package-lock.json
- packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-sL0hyu/index.released.pretty.json	2023-11-30 15:56:09.000000000 +0100
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-sL0hyu/index.prepared.pretty.json	2023-11-30 15:56:12.000000000 +0100
@@ -32,7 +32,50 @@
"javascript.operators.await",
"javascript.statements.async_function"
],
-    "spec": "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-async-function-definitions"
+    "spec": "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-async-function-definitions",
+    "status": {
+      "baseline": "high",
+      "baseline_low_date": "2017-04-05",
+ …
```
> 📦 Release web-features@0.5.0-alpha.0

- feature-group-definitions/scheduler.yml
| Key                                                                                                                                                                       |    Baseline    | Low since date | Versions                                                                                                       |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------: | :------------- | -------------------------------------------------------------------------------------------------------------- |
| **scheduler** …
> `scheduler`: set Baseline status (and correct feature list)

- feature-group-definitions/webusb.yml
I removed a non-existent feature here.
| Key                                                                                                                                                                                                       |    Baseline    | Low since date | Versions                                                                                                          |
| :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :------------: | :------------- | ----------------------------------------------------------------------------------------------------------------- |
| **webusb** …
> `webusb`: revise feature list and set Baseline status

- feature-group-definitions/masonry.yml
| Key                                                                                                                                            |    Baseline    | Low since date | Versions                                                                                                             |
| :--------------------------------------------------------------------------------------------------------------------------------------------- | :------------: | :------------- | -------------------------------------------------------------------------------------------------------------------- |
| **masonry**                                                                                                                                    | ❌ Not Baseline |                | Chrome ❌<br>Chrome …
> `masonry`: set Baseline status (and correct feature list)

- feature-group-definitions/default.yml
Separating `default` out from https://github.com/web-platform-dx/web-features/pull/455/.
| Key                   | Baseline | Low since date | Versions                                                                                                            |
| :-------------------- | :------: | :------------- | ------------------------------------------------------------------------------------------------------------------- |
| **default**           |  ✅ High  | 2020-01-15     | Chrome 10<br>Chrome Android 18<br>Edge 79 🔑💎<br>Firefox 4<br>Firefox for Android 4<br>Safari 5<br>Safari on iOS 5 |
| css.selectors.default |  ✅ High  | 2020-01-15     | Chrome 10<br>Chrome Android 18<br>Edge 79 🔑💎<br>Firefox 4<br>Firefox for Android 4<br>Safari 5<br>Safari on iOS 5 |
> `default`: set Baseline status

- index.ts
- schemas/defs.schema.json
This disposes of the old `is_baseline` and `since` fields, striking them from the schema.
Blocked on:
- #450 
- #451 
- #452
> Remove old Baseline definition schema fields

- feature-group-definitions/view-transitions.yml
- feature-group-definitions/webcodecs.yml
- feature-group-definitions/webvtt.yml
- feature-group-definitions/where.yml
| Key                                                                                                                                           |    Baseline    | Low since date | Versions                                                                                                          |
| :-------------------------------------------------------------------------------------------------------------------------------------------- | :------------: | :------------- | ----------------------------------------------------------------------------------------------------------------- |
| **view-transitions**                                                                                                                          | ❌ Not Baseline |                | Chrome 111<br>Chrome …
> Features V-W: set Baseline status

- .github/dependabot.yml
- packages/web-features/package-lock.json
- packages/web-features/package.json
When putting out the pre-releases, `npm` advised running `npm pkg fix` to correct the discrepancy between the actual repo and the `url` field. This corrects that.
In the process of reviewing the above, I also noticed that we use a different version of typescript for packaging than we do the rest of the project. Turning on dependabot for the published package should correct this.
> `web-features` `package.json` tidying

- package.json
- scripts/schema.ts
Inspired by https://github.com/web-platform-dx/web-features/pull/481 and other PRs.
Previously, we don't do anything to ensure that the JSON schema generator is doing so consistently from one version to the next, or that the generated schema is not stale. This will hopefully fix both issues, by asserting that the generated schema matches the schema on disk.
> Check consistency of TS types and JSON schema

- feature-group-definitions/scrollintoview.yml
- feature-group-definitions/set-methods.yml
- feature-group-definitions/shadow-dom.yml
- feature-group-definitions/sticky-positioning.yml
| Key                                                                                                                     | Baseline | Low since date | Versions                                                                                                                |
| :---------------------------------------------------------------------------------------------------------------------- | :------: | :------------- | ----------------------------------------------------------------------------------------------------------------------- |
| **scrollintoview**                                                                                                      |  ✅ High  | 2020-09-16     | Chrome 61<br>Chrome Android 61<br>Edge 79<br>Firefox 36<br>Firefox for Android 36<br>Safari 14 …
> Features starting with S: set Baseline statuses

- packages/web-features/package-lock.json
- packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-Uuhl35/index.released.pretty.json	2023-12-12 13:18:33.111428146 +0100
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-Uuhl35/index.prepared.pretty.json	2023-12-12 13:18:35.255649581 +0100
@@ -6,7 +6,20 @@
"compat_features": [
"javascript.builtins.Array.at"
],
-    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at"
+    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at",
+    "status": {
+      "baseline": "low",
+      "baseline_low_date": "2022-03-15",
+      "support": {
+        "chrome": "92",
+        "chrome_android": "92",
+ …
```
> 📦 Release web-features@0.5.0-alpha.2

- feature-group-definitions/offscreen-canvas.yml
- feature-group-definitions/overflow-shorthand.yml
- feature-group-definitions/popover.yml
- feature-group-definitions/read-write-pseudo-classes.yml
- feature-group-definitions/registered-custom-properties.yml
| Key                                                                                                                                                                 | Baseline | Low since date | Versions                                                                                                                      |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------: | :------------- | ----------------------------------------------------------------------------------------------------------------------------- |
| **offscreen-canvas** …
> Features O-R: set Baseline status

- feature-group-definitions/has.yml
- feature-group-definitions/idle-detection.yml
- feature-group-definitions/import-maps.yml
- feature-group-definitions/indeterminate.yml
- feature-group-definitions/is.yml
| Key                                                                                          |    Baseline    | Low since date | Versions                                                                                                                          |
| :------------------------------------------------------------------------------------------- | :------------: | :------------- | --------------------------------------------------------------------------------------------------------------------------------- |
| **has**                                                                                      | ❌ Not Baseline |                | Chrome 105<br>Chrome Android 105<br>Edge 105<br>Firefox 121 🚧<br>Firefox for Android 121 🚧<br>Safari 15.4<br>Safari on iOS 15.4 |
| …
> `has`, `i*` (excluding `input-event`): set Baseline statuses

- docs/baseline.md
This PR moves the "due for review" date to the "Ownership and maintenance" section of the Baseline doc.
As @tidoust noted in https://github.com/web-platform-dx/web-features/pull/423#discussion_r1410847301, the existing phrasing is somewhat over determined. It suggests that the duration and only the duration would come up for review. This conflicts with the governance text that says that reviewing and revising the definition (in general) is on the agenda annually. This PR attempts to reconcile the competing texts.
> Move Baseline status definition review date text

- feature-group-definitions/input-event.yml
I'm somewhat skeptical of this one. Safari has two issues:
- `InputEvent()` is listed as partial, due to missing some options on the constructor. I wonder if anyone's checked on this recently.
- `isComposing` was added later. This looks right.
Without the former, this is a newly available feature; without the latter, it's widely supported.
| Key                                                                                                                             |    Baseline    | Low since date | Versions                                                                                                                    |
| :------------------------------------------------------------------------------------------------------------------------------ | :------------: | :------------- | …
> `input-event`: set Baseline status

- feature-group-definitions/edit-context.yml
Blocked on https://github.com/mdn/browser-compat-data/pull/21603, probably.
> `edit-context`: Add EditContext API feature

- feature-group-definitions/input-event.yml
See the BCD change: https://github.com/mdn/browser-compat-data/pull/21640
(I can only recommend to get the `compat_features` from BCD directly using BCD's `tags`. Moves like this are somewhat rare but they happen. I think https://github.com/web-platform-dx/web-features/pull/489 switches to use BCD's tags?)
> Find input_event on api.Element

- feature-group-definitions/has.yml
I guess css-has is now baseline low?
People want to see this updated on MDN https://github.com/mdn/browser-compat-data/issues/21682 ...
(I really don't want to author PRs like this one. I maintain BCD on a daily basis and also maintaining compat-data in another repo is not a good use of time. BCD has a `support` object with the same and **up-to-date** info as in this file. BCD could also export computed baseline statuses as well if needed. There is no need to record/maintain this info twice.)
> Mark css-has baseline low

- feature-group-definitions/popover.yml
See https://github.com/mdn/browser-compat-data/pull/21875 for the move in BCD.
Like I said in https://github.com/web-platform-dx/web-features/pull/513, I can only recommend to get the `compat_features` from BCD directly using BCD's `tags`. See also https://github.com/web-platform-dx/web-features/pull/489 which I think switches us to use BCD's tags.
> Find popover attributes on input/button elements

- .gitignore
- index.ts
- package.json
- packages/web-features/index.ts
- packages/web-features/package-lock.json
- packages/web-features/package.json
- scripts/build.ts
- types.ts
Including TypeScript type definitions makes it somewhat easier to consume `web-features` in TypeScript code (which I'm now doing in the process of generating burndown lists for web-features to BCD, caniuse, and MDN pages). Also, this was requested by @LeoMcA.
I'll self-review to highlight or explain some bits.
You can test this out by doing these steps:
1. Check out this branch.
2. Run `npm install`, `npm run build`, then `cd packages/web-features && npm pack`. This generates a zip file containing the built package, as if it were on npm.
3. Take that zip file somewhere else, run `npm install <zip>` and try using `import webFeatures from "web-features"`. Voilà: types.
> Publish types in `web-features` package

- feature-group-definitions/server-timing.yml
See https://github.com/mdn/browser-compat-data/pull/22110
Drive-by comment: analog to the caniuse pointer, I wondered if there should be BCD (and WPT) pointers:
```
name: "Server timing"
spec: https://w3c.github.io/server-timing
bcd: server-timing
caniuse: server-timing
wpt: server-timing
```
> Add a group for Server Timing

- feature-group-definitions/canvas-context-lost.yml
- feature-group-definitions/svg2-script-html-equivalence.yml
- feature-group-definitions/trusted-types.yml
Omit the "event" suffix and use "and" instead of "&".
Use sentence case.
> Adjust names of some features

- feature-group-definitions/modulepreload.yml
- Is this a reasonable spec link for the feature? Is it a reasonable caniuse reference?
> Add `modulepreload` feature for `<link rel="modulepreload">`

- feature-group-definitions/search-input-type.yml
Corresponds to https://caniuse.com/input-search
- Is this a recognizable web feature to web developers? (caniuse features are often made by request, so it's likely, but let's double check our work here.)
> Add `<input type="search">` feature

- scripts/caniuse.ts
`@types/caniuse-lite` is up-to-date with the schema now.
> Remove no-longer needed caniuse type declaration

- package-lock.json
- package.json
- scripts/specs.ts
New version of web-specs contains the ISO spec for JPEG XL (see #580), but adding that spec, which does not have a public version, required making a breaking change in web-specs, to allow entries without a `nightly` property.
This update adjusts the code that processes web-specs entries accordingly, and removes the JPEG XL exception as it is no longer needed.
> Bump web-specs from 2.79.0 to 3.0.0 and adjust code accordingly

- packages/web-features/README.md
The syntax has changed, and we don't really need this example.
> Remove import assertions from README

- feature-group-definitions/individual-transforms.yml
The shortest plausible name for this is "translate, scale, and rotate",
but these are concepts that appear also in DOMMatrix and 2D canvas, so
to disambigutate include "CSS" as a prefix. Also include "properties" as
a suffix to make it clear that it's no about the ability to
translate/scale/rotate, which the `transform` property has, but the
indivudal properties.
> Add feature for individual transform properties

- feature-group-definitions/array-at.yml
- feature-group-definitions/array-flat.yml
- feature-group-definitions/async-await.yml
- feature-group-definitions/bigint.yml
- feature-group-definitions/class-syntax.yml
- index.ts
As proposed by @foolip in https://github.com/web-platform-dx/web-features/pull/624#discussion_r1491166953 
I like snapshot tags in BCD: it's easy to find features that very likely belong to the same bundle. I'm not adding more to this PR, but for example for Classes and BigInt, I already see that we could add more BCD compat_features that were introduced in the same ecmascript snapshot.
> Add experimental snapshot field (not published)

- feature-group-definitions/avif.yml
Opening this after seeing @captainbrosset post https://mas.to/@patrickbrosset/111606297691549413.
Leaving this as draft until Edge 121 is released. The versions for the other browsers also need to be confirmed.
> Mark AVIF as Baseline low

- scripts/schema.ts
Because validate() was called without awaiting the result, if validate()
was actually async and would fail after some time, this script would
exit with success before that happened.
> Remove unneeded async keyword in schema validation script

- feature-group-definitions/array-isarray.yml
- feature-group-definitions/array-iteration-methods.yml
- feature-group-definitions/array-splice.yml
- feature-group-definitions/array.yml
- feature-group-definitions/text-indent.yml
- feature-group-definitions/typed-arrays.yml
This was updated in BCD in https://github.com/mdn/browser-compat-data/pull/22286.
> Update Baseline dates to refect Edge 12 release date

- feature-group-definitions/promise-allsettled.yml
- feature-group-definitions/promise-any.yml
- feature-group-definitions/promise-finally.yml
- feature-group-definitions/promise-withresolvers.yml
- feature-group-definitions/promises.yml
The tour through ECMAScript continues...
(if we had capability groups, I would connect all _bundles_ in this PR to the _group_ "Promises").
Interesting to me was Promise.withResolvers: BCD records Safari 17.4 already but it is not a released version yet. So, it is not baseline low until we have observed the final release of Safari 17.4 with its release date. It is likely it will be baseline low soon, though.
> Add Promise features

- docs/README.md
Add more examples and document the additional shortening from names to
identifiers that we've done in many cases.
> Refactor docs to cover both names and identifiers

- feature-group-definitions/long-animation-frame-timing.yaml
- feature-group-definitions/navigation-activation.yml
Another example PR for bundles that could be exported to web-features when we run the OWD BCD collector for new browser versions and new features shipping with them: https://github.com/mdn/browser-compat-data/pull/22280
I'm pretty sure a bundle for "Long Animation Frame Timing" makes sense. 
For "Navigation Activation", I don't know if this part of something larger. It has its own entry on Chromestatus at least.
> Add Long Animation Frame Timing

- feature-group-definitions/visual-viewport.yml
Include "API" in the name as visual viewport is a concept in its own
right which is also touched by other web-exposed features:
https://drafts.csswg.org/css-viewport/#interactive-widget-section
The entry point to the API is `window.visualViewport` or just
`visualViewport`, so those are also plausible names.
Since there's no plain "visual viewport" feature to add to web-features,
don't include API in the identifier.
> Add visual viewport API feature

- feature-group-definitions/bluetooth.yml
- feature-group-definitions/web-bluetooth.yml
This depends on https://github.com/mdn/browser-compat-data/pull/22627 which introduces the `web-features:bluetooth` tag to the corresponding BCD entries.
> Adding the Web Bluetooth API feature

- feature-group-definitions/midi.yml
- feature-group-definitions/web-midi.yml
This depends on https://github.com/mdn/browser-compat-data/pull/22626 which adds the `web-features:midi` tag to the corresponding BCD entries.
> Adding the Web MIDI API feature

- feature-group-definitions/read-write-pseudos.yml
This is a shorter name, and matches the style of user-pseudos: https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/user-pseudos.yml
> Rename read-write-pseudo-classes to read-write-pseudos

- feature-group-definitions/scroll-into-view.yml
Hyphenation of identifiers is not covered by our guidlines, but it is the emergent convention for other features named after methods, like checkVisibility() structuredClone().
> Rename scrollintoview to scroll-into-view

- feature-group-definitions/masonry.yml
The BCD entries for this feature have already been added to the BCD as tags, no need to repeat them here (see this [search query](https://github.com/search?q=repo%3Amdn%2Fbrowser-compat-data%20%22web-features%3Amasonry%22&type=code)).
This PR also adds a short description of the feature.
> [Masonry] Adding a description and removing compat features

- feature-group-definitions/transforms2d.yml
- feature-group-definitions/transforms3d.yml
Because transforms exist in multiple other parts of the platform
(DOMMatrix, canvas, SVG) prefix the names with "CSS".
> Add CSS 2D/3D transform features

- feature-group-definitions/counter-style.yml
Note that when we set a status for this one, it might get a little weird: BCD says `speak-as` is not widely supported, but I'm not sure that's correct (e.g., I couldn't find a webkit bug about it). The rest of this seems boring and unobjectionable.
> Add `counter-style`

- scripts/specs.ts
I am often forgetting to set the level for CSS specs. This does an OK job of suggesting something better in those cases. We might extend this further to catch typos and the like.
> Suggest-a-spec

- feature-group-definitions/promise-withresolvers.yml
Safari 17.4 has been out since March 5, so it's now Baseline low.
> promise-withresolvers: Baseline low as of 2024-03-05

- scripts/specs.ts
https://github.com/w3c/browser-specs/blob/main/README.md#standing
There are no exceptions to this rule now, but exceptions could still be
made via defaultAllowlist.
BCD also has this rule:
https://github.com/mdn/browser-compat-data/blob/fd1cb702c59712fc3ef2056ed3a846292e3ae8c3/test/linter/test-spec-urls.ts#L43
> Only allow specs in "good" standing

- feature-group-definitions/relative-color.yml
Section `5.1` is only about `color(from ...)`.
While section `4` is a better general introduction to relative colors.
`https://drafts.csswg.org/css-color-5/#relative-colors` links to section `4`
> Update `spec` link for Relative colors

- feature-group-definitions/color-scheme.yml
- feature-group-definitions/light-dark.yml
- feature-group-definitions/prefers-color-scheme.yml
These three features are all related to dark mode.
> Add prefers-color-scheme / color-scheme / light-dark()

- docs/baseline.md
This adds an item to non-goals to clarify that support in assistive tools that may be used along a browser is not (yet?) covered by Baseline.
See discussion in https://github.com/web-platform-dx/web-features/issues/498
> Clarify that Baseline does not cover assistive technology

- feature-group-definitions/mathml.yml
This is a likely Baseline 2023 feature.
> `mathml`: Add MathML (also known as MathML Core)

- feature-group-definitions/compression-streams.yml
The supported compression types are also part of this and have a support history equivalent to that of the constructors themselves.
This improves coverage of Baseline 2023 compat keys.
> `compression-streams`: add compression types

- feature-group-definitions/font-variant-alternates.yml
These are closely related—the at-rule sets values for `font-variant-alternates` to use—so I've added to the feature rather than creating a second one.
This does not have any impact on the Baseline 2023 support status.
> `font-variant-alternates`: add `@font-feature-values` at-rule

- .github/dependabot.yml
- packages/compute-baseline/package-lock.json
- packages/compute-baseline/src/baseline/index.test.ts
- packages/compute-baseline/src/baseline/index.test.ts.snap
This does three things:
- Turn on Dependabot upgrades for `compute-baseline`
- Upgrades `compute-baseline`'s BCD to the latest version
- Fixes a test and test snapshot to reflect a change in BCD's release date for Edge 12
> Upgrade compute-baseline dependencies automatically

- .prettierignore
- packages/web-features/README.md
- packages/web-features/index.ts
As written before, it opted-out directories too. This makes adding more files to the configuration a bit of a pain: you have to opt-in the directory first. This PR fixes that (and cleans up a couple files probably erroneously left out).
> Make `.prettierignore` opt-ins easier to apply

- feature-group-definitions/font-face.yml
This matches the syntax, and "fonts" is very generic.
> Rename fonts to font-face

- packages/compute-baseline/src/baseline/index.test.ts
- packages/compute-baseline/src/baseline/index.ts
Presently, an actual Baseline `"low"` status can result in an erroneous `"high"` status with a future-dated `baseline_high_date`. For example, given the keystone date of 2024-04-04 (today), you'd get this back:
```js
{
baseline: "high",
baseline_low_date: "2024-04-04",
baseline_high_date: "2026-10-04"
}
```
This PR fixes the faulty check for future `baseline_high_date` values and puts in some tests to prevent it from happening again.
> `compute-baseline`: fix incorrect status for future-dated "high" statuses

- feature-group-definitions/class-syntax.yml
I _think_ this belongs with the rest of the class syntax stuff (excluding the private class properties stuff).
Inspired by looking at this feature for https://github.com/web-platform-dx/web-features/pull/751/files#r1547468185.
> `class-syntax`: Add `super` operator

- packages/compute-baseline/src/browser-compat-data/compat.test.ts
- packages/compute-baseline/src/browser-compat-data/compat.ts
- packages/compute-baseline/src/browser-compat-data/feature.test.ts
- packages/compute-baseline/src/browser-compat-data/feature.ts
This PR adds two new helpers to compute-baseline:
- A `walk()` generator on `Compat`, to offer something a bit like BCD's `traverse` command. This code (mostly) already exists, just not attached to the `Compat` interface.
- A `tags` getter on feature objects, to have checking for an array of tags in a BCD `__compat` object in one place.
This is the last of the table setting for generating statuses from authored YAML files.
> Add utilities for finding BCD tag data

- feature-group-definitions/appearance.yml
- feature-group-definitions/map.yml
- feature-group-definitions/modulepreload.yml
One has been removed:
https://github.com/mdn/browser-compat-data/pull/22546
The others look like typos.
> Fix broken BCD paths in compat_keys

- feature-group-definitions/storage-buckets.yml
This is the use counter linked from https://chromestatus.com/feature/5739224579964928
> Add use counter for storage buckets

- .prettierignore
- packages/compute-baseline/src/baseline/index.test.ts
- scripts/find-troublesome-ancestors.ts
This PR tests the `withAncestors` option. There are two things in this PR:
1. A test that asserts that the results of the Baseline calculation `api.Notification.body` is different with and without ancestor features (i.e., the reported support for `api.Notification.body` is _greater_ than the reported supported for `api.Notification` and `api.Notification.body`).
Why is this important? See the MDN page [Notification: body property](https://developer.mozilla.org/en-US/docs/Web/API/Notification/body#browser_compatibility) and compare it to what you see in [Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification#browser_compatibility).
If you look at [this gist of such features](https://gist.github.com/ddbeck/e3e78201c60170152b020fc983bb163b) you'll see that there are …
> Test `computeBaseline`'s `withAncestors` option

- feature-group-definitions/compute-pressure.yml
Compat features are tagged in BCD: https://github.com/mdn/browser-compat-data/pull/22687
Not sure if https://chromestatus.com/metrics/feature/timeline/popularity/3900 (PressureObserver_Observe) is the best use counter, cc @kenchris
> Add Compute Pressure API

- feature-group-definitions/line-clamp.yml
We will most likely need to handle this feature manually and decide if we want it to cover just the unprefixed `line-clamp` or also `-webkit-line-clamp`. To avoid computing anything automatically, remove the compat keys.
> Remove compat keys for line-clamp

- .github/labeler.yml
The pre-existing label has a space.
> Fix label name in labeler.yml

- .github/dependabot.yml
In https://github.com/web-platform-dx/web-features/pull/891, I made a change to `dependabot.yml` that was invalid. The combination of `package-ecosystem` and `directory` must be unique, so I can't selectively widen and increase certain dependencies in one `package.json`. Here's hoping the defaults do something reasonable.
> Unbreak the dependabot config

- packages/compute-baseline/src/baseline/index.test.ts
- packages/compute-baseline/src/baseline/index.ts
- packages/compute-baseline/src/browser-compat-data/feature.ts
- scripts/dist.ts
This PR changes compute-baseline to always set Baseline to false for features marked as deprecated, obsolete, legacy, or otherwise discouraged from use.
Fixes https://github.com/web-platform-dx/web-features/issues/864
> Set Baseline to `false` for deprecated features

- index.ts
This is to ensure all new features have a description as we're working
out the Markdown/HTML details for publishing.
> Make description required without publishing them

- packages/compute-baseline/src/baseline/index.ts
While I was here, I improved the legibility of tab completion by getting rid of the indirection to the `FeatureSelector` interface.
> `compute-baseline`: Make `withAncestors` optional

- index.ts
Shorten two CSS function features, the longest of which was 56
characters long. The remaining names that list function names consists
of 3 functions or less.
The longest remaining name is 43 characters long:
ARIA attribute reflection (initial support)
> Limit the length of names to 80 characters

- packages/compute-baseline/package.json
Once I have this, I can do the first publishing to npm for `compute-baseline`. I'll start with a `next` tag, like we do for the incremental pre-releases of `web-features`.
> `compute-baseline`: Mark package as not private for first initial release

- .github/workflows/publish_next_compute-baseline.yml
- .github/workflows/publish_next_web-features.yml
This PR does two things:
- Automatically publishes `compute-baseline` as a `next`-tagged release to npm, when changes take place on files that might plausibly impact the package
- Filters publishing `web-features` only to files that migh plausibly impact _that_ package (i.e., we're not constantly publishing new releases when unrelated changes happen)
(I've already updated the npm token to allow publishing `compute-baseline`, so this should start working on the first merge after this PR merges.)
> GitHub Actions: Automatically publish compute-baseline (next) on changes

- feature-group-definitions/flexbox-gap.dist.yml
- feature-group-definitions/flexbox-gap.yml
- feature-group-definitions/flexbox.dist.yml
- feature-group-definitions/flexbox.yml
- feature-group-definitions/grid.dist.yml
- feature-group-definitions/grid.yml
- feature-group-definitions/masonry.dist.yml
- feature-group-definitions/masonry.yml
- feature-group-definitions/subgrid.dist.yml
- feature-group-definitions/subgrid.yml
- groups/layout.yml
Only include features that are unambiguously layout features and not
borderline. `anchor-positioning` and `aspect-ratio` are such borderline
cases, which do affect size and/or position, but aren't full layout
models like Grid is.
> Add a group for CSS layout

- feature-group-definitions/sanitizer.yml
This was removed from Chrome:
https://chromestatus.com/feature/5115076981293056
A part of it has shipped as a separate feature:
https://github.com/web-platform-dx/web-features/pull/999
> Remove Sanitizer API

- packages/compute-baseline/src/baseline/core-browser-set.ts
- packages/compute-baseline/src/baseline/date-utils.test.ts
- packages/compute-baseline/src/baseline/date-utils.ts
- packages/compute-baseline/src/baseline/index.test.ts
- packages/compute-baseline/src/baseline/index.ts
- packages/compute-baseline/src/baseline/support.test.ts
- packages/compute-baseline/src/baseline/support.ts
- packages/compute-baseline/src/browser-compat-data/browser.test.ts
- packages/compute-baseline/src/browser-compat-data/browser.ts
- packages/compute-baseline/src/browser-compat-data/compat.test.ts
- packages/compute-baseline/src/browser-compat-data/compat.ts
- packages/compute-baseline/src/browser-compat-data/feature.test.ts
- packages/compute-baseline/src/browser-compat-data/feature.ts
- packages/compute-baseline/src/browser-compat-data/index.ts
- packages/compute-baseline/src/browser-compat-data/query.test.ts
- packages/compute-baseline/src/browser-compat-data/query.ts
- packages/compute-baseline/src/browser-compat-data/release.test.ts
- packages/compute-baseline/src/browser-compat-data/release.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.test.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.ts
- packages/compute-baseline/src/browser-compat-data/walk.ts
- packages/compute-baseline/src/browser-compat-data/walkUtils.ts
- packages/compute-baseline/src/index.ts
- packages/compute-baseline/tsconfig.json
This adds the `.js` extension to imports in `compute-baseline`, so that consumers who don't use a bundler can still use the package.
Since I was touching almost every import, I also used VS Code's "organize imports" to impose a more consistent ordering of imports.
Fixes #967 (hopefully).
> `compute-baseline`: Add `.js` (and organize) imports and exports

- features/typed-arrays.yml
This seems like a simple omission. BCD data is the same as for
Uint16Array so this won't affect any later computed status.
> Add Uint32Array to typed arrays feature

- features/constraint-validation.dist.yml
- features/constraint-validation.yml
There is a small remaining difference left as a TODO.
> Align constraint validation API more with caniuse

- scripts/feature-init.ts
This adds the required `name` and `description` fields, to make it easier to stub out a new feature.
> `feature-init` command: add more mandatory fields

- features/masks.dist.yml
- features/masks.yml
2023-12-05 appears to be a simple mistake in https://github.com/web-platform-dx/web-features/pull/1037.
More issues in BCD were found, so update the PR link.
> Update Baseline date and TODO of CSS masks

- features/check-visibility.dist.yml
- features/check-visibility.yml
BCD was wrong, and fixing it will make this a Baseline 2024 feature.
Fixes https://github.com/web-platform-dx/web-features/issues/1124.
> Update checkVisibility() as Baseline low

- features/css-modules.dist.yml
- features/css-modules.yml
Fixes https://github.com/web-platform-dx/web-features/issues/1164.
> Remove import statement from CSS modules feature

- index.ts
This prevents a problem like in https://github.com/web-platform-dx/web-features/issues/1164
from happening before we have a way to handle it.
> Ensure that BCD keys are only used once

- scripts/dist.ts
This prevents `.dist` files from hanging around even after the authored YAML has been deleted.
Inspired by https://github.com/web-platform-dx/web-features/pull/1205
> Catch orphaned dist files during `--check`

- .github/workflows/refresh_dist.yml
This PR adds a GitHub Actions workflow that lets reviewers request a dist file refresh by adding a `refresh dist` label to the pull request. It only refreshes dists where the dist or authored YAML has changed on the PR, relative to the target branch.
A known limitation: this will only work for owners/peers on the repo, who can set labels on a PR.
> Add dist refresh workflow

- .vscode/settings.json
For contributors using VS Code, this configuration change marks `.dist` files as read-only, so it's harder to accidentally edit a dist file. Less likely now with the compact dists, but a convenience nonetheless.
> Mark dist files as read-only in VS Code

- features/draft/html-elements/README.md
- package.json
- scripts/dist.ts
The "**" path pattern in package.json doesn't work on at least macOS,
and contributed to an orphaned dist file:
https://github.com/web-platform-dx/web-features/pull/1205.
To avoid such issues, let the command expand directory names to any dist
files within, and make the dist script crawl all features by default.
This also allows simplifiying instructions in a README.
> Make the dist script crawl all features by default

- .github/workflows/refresh_dist.yml
This is for PRs like https://github.com/web-platform-dx/web-features/pull/1223 where no individual feature file has changed, but there are still dist updates to be made.
(A follow-on would be a workflow that automatically labels dependabot PRs with refresh dist.)
> Refresh all dists on `package.json` file changes

- package-lock.json
- packages/compute-baseline/package.json
- packages/compute-baseline/src/browser-compat-data/compat.ts
I think this will fix the issue reported by @tidoust in https://github.com/web-platform-dx/web-features/issues/967#issuecomment-2096339885.
This change will require one of Node.js ~~v16.14.0+~~ (see https://github.com/web-platform-dx/web-features/pull/1051#issuecomment-2100565931), v18.20.0+, or v20.10.0+.
If you want to test this immediately, do the following:
1. Check out this PR's branch.
2. Run `npm pack --workspace compute-baseline`. A `.tgz` file for the package is built.
3. In your project, install the `.tgz` file. For example, run `npm install ../path/to/compute-baseline-0.1.0.tgz`.
> `compute-baseline`: Use JSON import attribute when importing BCD

- features/draft/speech-recognition.yml
This was accidentally removed in https://github.com/web-platform-dx/web-features/pull/1162.
It's not clear how the accident happened, but this is the only source
*.yml file removed, all other file removals were *.dist.yml, confirmed
through `git show --stat c25032062c3211d7ffa6dcbc86bfb631eb648ba3 --diff-filter=D`.
> Reinstate speech recognition draft feature

- .gitignore
- package-lock.json
- package.json
- packages/compute-baseline/package.json
- packages/compute-baseline/src/baseline/date-utils.ts
I've had a branch sitting around to check how well-covered the compute-baseline code is. c8 fixed the bug preventing that, so now I can open this PR.
Right now it's not required for anything. More for the curious than anything else, though I did make a small change to remove unnecessary code in exercising this.
> Add code coverage for compute-baseline

- .github/workflows/refresh_dist.yml
- .github/workflows/remove_refresh_dist_label.yml
This PR is meant to improve the behavior of the dist refresh workflow, when the contributor's PR is from a fork.
This is needed because we can't (safely) trust the branch PR to modify labels on the web-features repo or assume that the PR is coming from a branch on this repository.
It's a bit convoluted, but here's how it works:
1. The first workflow starts when you label a PR with _refresh dist_. This workflow's permissions vary, depending on the author, originating repo, and the "Allow edits and access to secrets by maintainers" checkbox. In some cases, it won't have permissions to the `web-platform-dx/web-features` repo, so we can't do anything that assumes such permission.
1. It checks out contributor's repo and branch (whether that's `web-platform-dx/web-features` or a fork).
1. It …
> Refresh dist with forks

- .github/workflows/publish_next_compute-baseline.yml
- .github/workflows/publish_next_web-features.yml
- .github/workflows/pull_request.yml
In the course of https://github.com/web-platform-dx/web-features/pull/1252 and https://github.com/web-platform-dx/web-features/pull/1253, I noticed deprecation warnings on our workflow runs ([example](https://github.com/web-platform-dx/web-features/actions/runs/9520367729)). This PR upgrades the GitHub Actions steps (`actions/checkout` and `actions/node-setup`) that were triggering the deprecation warnings.
> Upgrade deprecated Node.js 16 actions to Node.js 20 actions

- .github/dependabot.yml
This will automatically generate PRs like #1255. Borrowed from [the Dependabot docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions).
> Turn on Dependabot upgrades for GitHub Actions

- .github/workflows/refresh_dist.yml
This fixes a failure like https://github.com/web-platform-dx/web-features/actions/runs/9513999419/job/26225227552?pr=1250 where the dependencies weren't installed because the conditional didn't take into account package.json changes.
> Dist refresh: run `npm install` in any case with changes

- features/search-input-type.yml
- features/search-input-type.yml.dist
- index.ts
- schemas/defs.schema.json
- scripts/dist.ts
- types.ts
The `use_ranges_before_baseline_low_date` field controls when generating
the status, but it could also be done in overrides.
Closes https://github.com/web-platform-dx/web-features/issues/1018.
> Allow use of ranges (≤) before the Baseline low date

- features/search-input-type.yml
- features/search-input-type.yml.dist
- index.ts
- schemas/defs.schema.json
- scripts/dist.ts
- types.ts
This complicates https://github.com/web-platform-dx/web-features/pull/1231 which is much more important for the velocity of the project, so back this out for now.
Reverts https://github.com/web-platform-dx/web-features/pull/1208.
> Revert "Allow use of ranges (≤) before the Baseline low date"

- features/container-queries.yml
Discovered thanks to https://github.com/web-platform-dx/web-features/pull/1231/ (https://github.com/web-platform-dx/web-features/pull/1231#discussion_r1660925264).
> `container-queries`: remove similarly-named but irrelevant compat keys

- packages/compute-baseline/src/browser-compat-data/feature.test.ts
- packages/compute-baseline/src/browser-compat-data/feature.ts
- scripts/update-drafts.ts
It's pretty clunky to do the `feature.data.__compat` + cleanup. I'd rather not think about the BCD schema, if I can help it. 😅
> `compute-baseline`: Add a couple of conveniences for spec and status data

- .prettierignore
- package.json
- scripts/build.ts
This is a little bit of prep to facilitate generating bare JSONs as GitHub release artifacts. `npx tsx ./scripts/build.ts` is now `npx tsx ./scripts/build.ts package`. That's it, for now.
Also, I applied prettier to this file. That was maybe a little bit of a mistake—the diff on the 2nd commit is more readable.
> Add CLI to `build.ts`

- packages/compute-baseline/src/browser-compat-data/supportStatements.test.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.ts
A very tiny step on the way toward "exploding" support statements into per-version y/n/unknown support information.
(Putting this PR in now, in the spirit of smaller PRs faster.)
> `compute-baseline`: Fix support statement `version_added` getter return type

- features/scroll-snap.yml.dist
- features/web-bluetooth.yml.dist
- scripts/dist.ts
For a few features, the comment was added incorrectly based on what the
computed status was, but the computed status is never written to dist if
the source includes an override.
> Fix incorrect "same status" comment when status override is used

- features/conic-gradients.yml
- features/conic-gradients.yml.dist
- features/font-palette-animation.yml
- features/font-size-adjust.yml
- features/font-size-adjust.yml.dist
- features/font-synthesis-position.yml
- features/font-synthesis-small-caps.yml
- features/font-synthesis-style.yml
- features/font-synthesis-weight.yml
- features/font-synthesis.yml
This resolves all warnings from `npm run dist` about this. For conic
gradients and font-size-adjust, the change in overall feature status
aligns with caniuse.com.
> Remove redundant compat_features lists

- features/contain-intrinsic-size.yml
- features/contain-intrinsic-size.yml.dist
This was already tagged in BCD, so use the tags.
Pin the feature status to the contain-intrinsic-size shorthand, since
the feature is usable with just that. This changes the Chrome and Edge
versions, but not the Baseline low date.
> Update contain-intrinsic-size to cover the `auto none` value

- packages/compute-baseline/src/baseline/date-utils.test.ts
- packages/compute-baseline/src/baseline/date-utils.ts
- packages/compute-baseline/src/baseline/index.test.ts
- packages/compute-baseline/src/baseline/index.ts
Fixes https://github.com/web-platform-dx/web-features/issues/1331.
> Use a cutoff date from BCD for Baseline high

- docs/README.md
This is really to fix the inconsistency that was there.
> Remove backticks from ranges describing valid identifiers

- index.ts
This is in order to simplify the schema:
https://github.com/web-platform-dx/web-features/pull/1060#discussion_r1664568229
> Validate identifers when reading features/groups/snapshots

- packages/compute-baseline/src/browser-compat-data/release.test.ts
- packages/compute-baseline/src/browser-compat-data/release.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.test.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.ts
This is another incremental step toward handling version ranges more completely, by taking a support statement and mapping it to _every_ release that a browser has.
More specifically, this PR:
- Adds `toReleaseSupportMap()` method to `SupportStatement`s. It's very much like `supportedBy()`, except it has something to say about every version, not just the supporting versions. I've made some of `supportedBy()` reusable. Eventually, but not today, we'll rip out `supportedBy()` entirely.
- Adds an `inRange(start, end?)` method to `Releases`s. This is a not-infrequent thing to check and remembering what `>= 0` means is hard.
- Remove some never-used code relating to ranges.
- Handle bugged `version_removed` values in BCD. Basically, some values should never happen according to the schema, but …
> `compute-baseline`: add method to expand a support statement into per-release support information

- packages/compute-baseline/src/baseline/support.ts
- packages/compute-baseline/src/browser-compat-data/feature.test.ts
- packages/compute-baseline/src/browser-compat-data/feature.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.test.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.ts
The main thing this does is gives us a way to quickly and unambiguously report `true`, `null,` or `false` for _unqualified_ support relationship between a release and a feature. There's some untidiness to clean up along the way. I'll self-review with commentary.
> `compute-baseline`: Add per-release support checks to `Feature`s

- scripts/release.ts
I wanted to compare two older releases and I repurposed some existing code to do it. I figure once we have automatic, scheduled releases, this will be a nice thing to have on hand.
> Add `diff` command as a package release debugging tool

- package.json
- packages/compute-baseline/package.json
- scripts/dist.ts
- scripts/update-drafts.ts
- tsconfig.json
Since we use `tsx` to run scripts, there's no explicit type checking `.ts` files outside of `compute-baseline`. Nevertheless, my editor shows type errors at editing time.
This PR makes two changes to fix this:
- Adds a `test:types` npm run command and includes it in the `test` command
- Fixes the (thankfully few) type errors reported.
> Turn on type checking everywhere and banish the red squiggles

- features/draft/text-box-trim.yml
- features/font-face.yml
- features/long-animation-frames.yaml
- features/promise.yml
- features/read-write-pseudos.yml
- features/scroll-into-view.yml
- features/viewport-unit-variants.yml
- features/viewport-units.yml
- schemas/defs.schema.json
- types.ts
This mechanism for renames hasn't been used by any consumers that we
know of.
A mechanism like this may not be needed at all, and if it is we may want
to design it a bit different to allow consumers to detect both deleted
and renamed identifiers.
Removing this now does not prevent us from reintroducing this as a "new"
feature if the need arises. If so, we may want to design it a bit
different to handle both deleted and renamed identifiers.
> Remove alias from the schema and all features

- .github/workflows/pull_request.yml
- .gitignore
- packages/web-features/index.ts
- packages/web-features/package.json
- scripts/build.ts
- scripts/release.ts
This is so that we can use the same filename in the NPM release and the
GitHub release. (index.json would be weird in a GitHub release.)
> Rename the JSON file in the web-feature package to data.json

- packages/web-features/README.md
Following https://github.com/web-platform-dx/web-features/pull/1470
> Document Node.js-less web-features import

- packages/web-features/README.md
This was tested with the 0.10.0 version of the package from NPM, but with index.json instead of data.json.
The previous syntax didn't work because these aren't named exports.
> Fix import syntax to work with Deno

- packages/web-features/package-lock.json
- packages/web-features/package.json
Hoorah.
Closes https://github.com/web-platform-dx/web-features/issues/735.
> Release web-features 1.0.0

- features/draft/indexeddb.yml
Just a missing letter.
https://github.com/crate-ci/typos
> Fix a typo in indexeddb

- features/input-event.yml
This is a special case. We use only the name of a lone event elsewhere (e.g., "scrollend"), but this event shares a name with the element ("\<input\>"). This moves the disambiguation text to parentheses to distinguish the name of the thing ("input").
Extracted from https://github.com/web-platform-dx/web-features/pull/1026.
> Retitle "input event" feature to "input (event)"

- index.ts
Prompted by the error in https://github.com/web-platform-dx/web-features/pull/1442
This narrowly fixes the cause of the error, though a broader change might be to only compute a baseline_high_date when the dist data doesn't already provide it.
> Handle version ranges in `index.ts` Baseline high calculations

- features/iframe-credentialless.yml
See discussion in https://github.com/web-platform-dx/web-features/pull/1468#discussion_r1687008988.
> Rename <iframe credentialless> feature

- .github/workflows/update_draft_features_weekly.yml
Reverts web-platform-dx/web-features#1517
> Revert "Give the draft updater workflow pull requests write permission"

- .github/workflows/update_draft_features_weekly.yml
- scripts/update-drafts.ts
And update dist, which was overlooked. These changes together will allow
the workflow to send PRs that pass the CI.
> Make the spec draft updater remove completed specs and work around nulls

- features/abbr.yml
- scripts/dist.ts
This was suggested by @Elchi3 as an initial step toward automatically checking good and bad uses of `compute_from`. Thank you, Florian!
> Disallow `compute_from` when it has no impact on the status

- scripts/dist.ts
Thanks to @Elchi3 for the suggestion in https://github.com/web-platform-dx/web-features/pull/1609#discussion_r1721674766.
> Make dist errors and warnings more explicit about fixes

- features/promise-any.yml
- features/promise-any.yml.dist
I think AggregateError should belong to the promise-any feature. 
This PR is also a bit of a process question: If we think that certain features should contain additional BCD keys, do we open a PR here in web-features to alter the feature's definition? (and sync the decision back to BCD later on?) or should things be synced in two ways (a PR updating tags in BCD would have been fine, too). I'm leaning towards just syncing from web-features to BCD for the moment, but curious to hear what others think.
> Add AggregateError to promise-any feature

- docs/CONTRIBUTING.md
I've been doing a lot explaining on this question: when do I create a new feature (versus adding a key and using a `compute_from` and so on)?
This is my attempt to provide a general answer (which is hard!—the specifics often matter).
> Contributing docs: add hints on lumping and splitting

- docs/CONTRIBUTING.md
Fixes https://github.com/web-platform-dx/web-features/issues/1600
> Contributing docs: add some first-time contributing hints

- features/font-optical-sizing.yml
- features/font-optical-sizing.yml.dist
The keywords were very likely added simultaneously to the property, so I suspect the `<=` values for the keywords could be adjusted in BCD.
> Add keywords to font optical sizing

- scripts/specs.ts
Previously, a missing or invalid spec URL would throw an error without a message. This change surfaces that error when running `npm run test:specs`.
In addition, the test was reporting the number of specs as the number of features, so now it reports both.
> Add catch for invalid spec URLs

- .prettierignore
This PR inverts the direction of the `.prettierignore` file, so that it lists the files and folders to ignore (as the file name implies), rather than all the files and folders to _only_ format.
In another PR (my first), the [first review comment](https://github.com/web-platform-dx/web-features/pull/1622#discussion_r1723110227) had requested that the new script was added to the `.prettierignore` file as an opt-in.  However, it is not standard to use a `.ignore` file for opting into formatting, so this was very confusing to me.  Additionally, since I'm assuming the plan is to eventually format all files using Prettier, having the `.prettierignore` file use an opt-out (or using proper terminology, _ignore_) structure, it serves as a to-do list for what still needs to be formatted.
> Invert .prettierignore (use opt-out, not opt-in)

- scripts/dist.ts
We erroneously stopped checking for this with https://github.com/web-platform-dx/web-features/pull/1343
> Reinstate check for `.dist` without `.yml` companion

- docs/guidelines.md
Fixes https://github.com/web-platform-dx/web-features/issues/1631
> Contributor docs: add `caniuse` usage guidance

- features/long-animation-frames.yaml
I came across this file and believe it is there by accident. Renaming it to `.yml` and running dist does not add any keys, so the tag doesn't appear to exist in BCD. Because it is a .yaml file, it is not included in data.json.
It was originally added in https://github.com/web-platform-dx/web-features/pull/645. @Elchi3 is there a reason this file should be kept?
> Remove long-animation-frames.yaml

- packages/compute-baseline/src/browser-compat-data/compat.ts
- scripts/dist.ts
If a contributor has not run `npm install` recently, then it's easy to get (surprising) messages from `dist.ts` about stale YAML files. This adds a preflight check to the dist script, to prevent this from happening.
This also adds a `version` getter to compute-baseline, which might affect the version number of the next compute-baseline release.
> Check for stale BCD before updating dist files

- docs/publishing.md
I just did a web-features release and made a few improvements to the publishing docs as I went. Hopefully this stuff will help me complete it a little faster next time:
- Explain where we're checking for unescaped HTML
- Provide Markdown literals for pasting into the release description
- Add follow up step for "version required" labels
- Add a regex hint for creating releases
- Use full stops consistently
- Number the steps
> Publishing docs: apply miscellaneous edits

- .github/workflows/labeler.yml
It's failing right now because the labeler doesn't use a checkout, so the repository must be explicitly set.
> Fix labeler failure due to missing repo environment variable

- scripts/migrate-to-bcd.ts
This adds environment variables for setting the path to BCD and a verbosity option.
Follow up from the discussion at https://github.com/web-platform-dx/web-features/pull/1622#discussion_r1724863422.
cc: @queengooborg Hopefully this accommodates everyone's config preferences (implicit, explicit, and environment variables).
> Extend migrate-to-bcd CLI

- GOVERNANCE.md
This PR is an attempt to modify the governance doc to reflect actual PR management practices, which have departed a little from what we initially proposed. Chiefly, this would allow peers to merge any feature change, with the exception of deleting a feature outright. I also made a few consistency edits along the way, to reflect the terminology we actually use.
Note: This is a governance change, so I'd like to have at least a few owners review and approve before merging (and block on any objections).
Fixes https://github.com/web-platform-dx/web-features/issues/1528.
> Update governance to allow peers to merge status changes

- features/text-wrap-mode.yml
- features/text-wrap-mode.yml.dist
Just adds `wrap` and `nowrap` keys, which were missed in #1698.
> Add missing text-wrap-mode keys

- features/contain-intrinsic-size.yml
- features/contain-intrinsic-size.yml.dist
Adds `.none` suffix to each key.
> Add missing keys to contain-intrinsic-size

- docs/guidelines.md
Fixes https://github.com/web-platform-dx/web-features/issues/1388
> Contributor docs: add guideline for literal code snippets and overlong entry points

- docs/guidelines.md
On today's WebDX call, there was a question about guidelines and what groups are for. A first attempt at recording when we do or do not group features.
> Contributor docs: add lightweight guidelines for grouping features

- .github/dependabot.yml
Upgrades to `packages/web-features` are a little weird, since it only changes the lockfile. This ought to upgrade them more in line with the top-level `package.json`.
> Let Dependabot upgrade web-features dev dependencies more strictly

- scripts/release.ts
Remove some unused code from a previous (and premature) attempt to automate the release process.
For https://github.com/web-platform-dx/web-features/pull/1769, I tried using `scripts/release.ts`, which was incomplete and predates our current release process, documented in [`publishing.md`](https://github.com/web-platform-dx/web-features/blob/1ef1f93dbf33d12f0e5a2f7fb095508675ad3ef5/docs/publishing.md#publishing).
It kinda works—I want to open a PR to fix what's broken—but there's also a lot of unused code that I don't foresee using, at least not in the same way. Some it might return in some form later, but I think deleting this unusued/untested procedure in favor of incrementally automating the documented process is a better path forward.
> Remove unused release script code

- docs/publishing.md
~~Blocked on https://github.com/web-platform-dx/web-features/pull/1650~~
> Publishing docs: document versioning policy

- scripts/dist.ts
This PR fixes #1768 by adding linting that checks if a `.yaml` file is detected instead of a `.yml` file.
Some editors (like mine) seem to prefer the `.yaml` extension instead of `.yml`, which causes the .dist files to not be generated.  Unfortunately, there is no warning message that states there's an invalid file, so this PR adds one in.  It also searches for any files of an invalid type and throws an error.
> Throw error if .yaml file is detected instead of .yml

- features/overlay.yml
- features/overlay.yml.dist
`auto` and `none` were missing, no changes to baseline.
> Add missing keys to overlay

- .github/labeler.yml
The previous config required all globs to match. That is to say, all the configuration files had to change for any PR to be labeled as tools and infra.
> Fix labeling tools and infrastructure PRs

- features/motion-path.yml.dist
I merged https://github.com/web-platform-dx/web-features/pull/1754 which I didn't notice had been waiting a little while and the dist turned out to be stale. This fixes the build failure.
> Refresh dist (to unbreak the build)

- features/individual-transforms.yml
This creates a stronger link to the "as opposed to" clause.
That said, another way to do this would be:
> The `translate`, `rotate`, and `scale` CSS properties apply simple transformations independently, as opposed to applying compound transformations with the `transform` CSS property.
> Revise `individual-transforms` description

- features/color-scheme.yml
- features/color-scheme.yml.dist
Doesn't impact baseline, just adds missing keys found in https://github.com/mdn/browser-compat-data/pull/24163.
> Add dark, light and normal keywords to color-scheme

- docs/guidelines.md
This describes an undocumented but widely-applied convention.
Fixes https://github.com/web-platform-dx/web-features/issues/1804.
> Contributor docs: recommend sentence case for names

- docs/CONTRIBUTING.md
- docs/README.md
- docs/reviewing.md
While the governance doc covers some _rules_, it doesn't catch some of our unwritten conventions. I've written this up in anticipation of [adding new peers](https://github.com/web-platform-dx/web-features/pull/1808).
> Contributor docs: write up merge practices

- scripts/dist.ts
This lets more files remain in the `features` directory—such as editor `.swp` files—without throwing an exception. 
Fixes https://github.com/web-platform-dx/web-features/issues/1789.
> `dist` script: be more permissive with file extensions

- scripts/feature-init.ts
Tiny QOL change- the first thing I want to do after running `feature-init` is open the newly generated file. This prints the path to the console, so I can click on it and open it.
> Print destination path on feature init

- features/grid.yml
- features/grid.yml.dist
I also fixed a typo in the description while I was here.
A quick follow up to https://github.com/web-platform-dx/web-features/pull/1854
> Align `grid` with caniuse

- features/list-style.yml
- features/list-style.yml.dist
This was accidentally removed in https://github.com/web-platform-dx/web-features/pull/1764, but it should be included, as it is part of the spec.
> Add missing cjk-ideographic key

- features/physical-properties.yml
A quick follow on to https://github.com/web-platform-dx/web-features/pull/1884 that names all the properties, since we have room for it.
> Revise physical properties description

- .github/workflows/update_draft_features_weekly.yml
I assume this is not very helpful for forks and it produces a lot of needless branches. I think we should make this opt-in for forks.
> Turn off drafts updater on forks

- .github/workflows/update_draft_features_weekly.yml
With the lighter-weight diffs introduced in https://github.com/web-platform-dx/web-features/pull/1783 it now makes sense to run this more frequently, so contributors are less likely to see already-assigned keys.
> `update-drafts`: increase frequency of updates

- .github/workflows/publish_next_web-features.yml
This is like the `web-features@next` release on npm, but on GitHub and extended to the bare JSON artifacts.
This is setup for https://github.com/web-platform-dx/web-features/issues/1860.
> Create a continuous prerelease for GitHub

- features/text-wrap-style.yml
- features/text-wrap-style.yml.dist
Key was added in latest BCD, supported by Safari 18 TP.
> Add text-wrap-style.pretty key

- features/symbol.yml
Following up on https://github.com/web-platform-dx/web-features/pull/1669
> Revise description for `symbol`

- features/console.yml
- features/console.yml.dist
Looks like oversight to me (see https://github.com/web-platform-dx/web-features/pull/1839 for the original PR)
> Add more keys to console feature

- features/font-variant-position.yml
- features/popover.yml
Eventually these should become some object representing a note. See https://github.com/web-platform-dx/web-features/issues/1971.
But until then a comment will do nicely.
> Add comments for features that regressed Baseline status

- features/resource-size.yml
**Before:**
> The decodedSize, encodedSize, and transferSize properties of the PerformanceResourceTiming API reports the size of resources loaded
**After:**
> The decodedBodySize, encodedBodySize, and transferSize properties of the PerformanceResourceTiming API reports the size of resources loaded
I know nothing about this feature, but this is what's documented at MDN.
> Fix decodedBodySize and encodedBodySize property names in resource-size description

- features/namespace.yml
The `name` field is non-Markdown plain text, unlike `description`.
> `namespace`: remove Markdown from the feature name

- features/web-nfc.yml
- features/web-nfc.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/web-nfc.yml
See also https://github.com/web-platform-dx/web-features/pull/1087 in which we didn't have `compute_from` yet, I assume. 
Not sure if we want to use `compute_from` here. The effect on the baseline status is basically none, I think.
> Add a key to WebNFC

- features/webgl.yml
- features/webgl.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webgl1.yml
(The SharedArrayBuffer keys seem like a separate feature to me, PR upcoming)
> Add more keys to WebGL

- features/background-sync.yml
- features/background-sync.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/background-sync.yml
I also introduced `compute_from` here so that the status remains the same.
> Add keys to Background sync

- .github/workflows/bcd_upgrade_checklist.yml
This workflow adds a checklist comment to dependabot PRs that have `@mdn/browser-compat-data` in the diff. This should help make the work around these PRs more consistent.
> Add checklist for handling BCD upgrades

- packages/web-features/package-lock.json
- packages/web-features/package.json
The brings us up to date with BCD v5.6.9, released yesterday. https://github.com/web-platform-dx/web-features/compare/v2.1.0...HEAD
> Prepare v2.2.0 release

- .github/workflows/bcd_upgrade_checklist.yml
A follow up to https://github.com/web-platform-dx/web-features/pull/2043.
This workflow on the first attempt: https://github.com/web-platform-dx/web-features/actions/runs/11496579249/job/31998472971?pr=2071#logs
Problems:
- No write permissions for the PR
- No checkout to run the diff against (I tested this bit and I have no idea why this worked on my own repo but not here, even though it obviously SHOULD have failed 🙄)
To fix this, I did these things:
- Switched to using https://github.com/dependabot/fetch-metadata instead (to avoid a slow checkout)
Unfortunately, this makes the PR basically untestable—you can't force Dependabot to do anything. We'll find out if it works tomorrow, I guess.
- Set `continue-on-error` for both steps, since failures of this workflow shouldn't mark the PR as …
> Fix checklist for BCD upgrades workflow

- .github/workflows/bcd_upgrade_checklist.yml
Now that I've actually used the checklist in https://github.com/web-platform-dx/web-features/pull/2088, I've made some revisions. Changes include:
- Avoiding an issue back reference that would repeat multiple times per week
- Be explicit about commits and pushes
- Change and group order of steps
> Revise BCD upgrade checklist

- .github/workflows/update_draft_features_weekly.yml
Actions-generated PRs won't trigger more workflow runs. This addition to the commit message says how to overcome this limitation.
> Update drafts workflow: document tests workaround

- features/intersection-observer.yml
- features/intersection-observer.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/intersection-observer.yml
Also use `compute_from`. I used `isIntersecting` so that the current status remains the same.
> Add more keys to Intersection observer

- features/relative-color.yml
This does not change keys, but just updates notes on relative colors.
Related issues-
- https://github.com/Fyrd/caniuse/issues/7191
- https://github.com/mdn/browser-compat-data/issues/24528
> Update notes on relative colors

- features/supports.yml
- features/supports.yml.dist
The linked issue says to sort this out on the long tail, which I think we're at. 
https://github.com/web-platform-dx/web-features/pull/1353#discussion_r1673871428
Essentially, `api.CSSImportRule.supportsText` has some data issues, but does not impact baseline. 
In looking into it, Chrome and Firefox data is correct. In both, the CSSOM portions were shipped first. In Chrome, that was accidental, and in Firefox, it was behind a flag in 114, but the CSSOM was still accessible.
For Safari, it looks like `css.at-rules.import.supports` should also be marked as 17.5. I opened https://github.com/mdn/browser-compat-data/issues/24842. I don't think this change needs to be blocked on that.
> Add CSSImportRule.supportsText key to @supports

- features/svg.yml
- features/svg.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/fill-stroke-3.yml
> Add a key to SVG

- docs/publishing.md
This is primarily a reminder to myself, since James asked for this previously.
I expect we'll eventually get rid of this step, if/when we version the schema itself. See https://github.com/web-platform-dx/web-features/issues/1704
> Publishing docs: add informing consumers to the release steps

- features/shape-outside.yml
- features/shape-outside.yml.dist
- features/shapes.yml
- features/shapes.yml.dist
No changes to baseline due to existing `compute_from`s.
> Add missing shape keys

- features/masks.yml
- features/masks.yml.dist
This sets a `compute_from` to not change the baseline status.
> Add missing keys to masks

- packages/web-features/package-lock.json
- packages/web-features/package.json
Release for BCD v5.6.11. https://github.com/web-platform-dx/web-features/compare/v2.3.0...4277ec4
As of 4277ec4:
- 1 new feature
- 63.5% coverage of BCD
> Prepare release v2.4.0

- towards-features.md
We haven't reviewed the "Towards a common list of web features" document since work on the web-features project started. It may contain content that we would no longer agree with, or that we would consider incomplete or outdated.
It could be worthwhile to revisit the document in a not too distant future. In the meantime, I'm proposing to add an introductory note to flag the document as historical.
Cc @captainbrosset, @atopal
> Flag the "Towards features" document as historical

- features/webgl-sab.yml
- features/webgl-sab.yml.dist
I missed this in https://github.com/web-platform-dx/web-features/pull/2067.
The WebGL2 draft feature also has additional keys (and I wasn't expecting this feature to be 30 keys large in total)
> Add more keys to SAB in WebGL

- features/serial.yml
- features/serial.yml.dist
https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API
> Add Web Serial

- .github/workflows/prepare_release.yml
- scripts/release-pull-description.md
- scripts/release.ts
This PR adds a workflow to run on demand for new releases. It's more of a proof of concept at this point—there's still some work to do to automatically clean up the release notes, prepopulate with some stats, and so on. But at very least, this means that one owner can cut a release, without the need for the (trivial) review of the `package.json` file.
> Add a semi-automated release workflow

- docs/publishing.md
This documents the new workflow added in https://github.com/web-platform-dx/web-features/pull/2191.
I don't need anyone to actually test this (I'll follow it on the next web-features release), but it'd be nice to have someone read through it.
> Publishing docs: update steps for new release workflow

- features/absolute-positioning.yml
- features/absolute-positioning.yml.dist
- features/grid.yml
- features/grid.yml.dist
- features/multi-column.yml
- features/multi-column.yml.dist
Root properties were added to where they were first supported.
(There are some remaining keys in css-align that will be dealt with separately)
> Add missing keys from css-align

- features/http11.yml
- features/http11.yml.dist
I think we wanted to do this a while ago but back then 1) BCD had no real version numbers for many HTTP/1.1 keys and 2) we had no `compute_from`.
> Add more keys to HTTP/1.1

- features/media-queries.yml
- features/media-queries.yml.dist
The BCD data here is incorrect, and should have full support- see https://github.com/mdn/browser-compat-data/issues/25034.
Since this feature has a compute_from, adding this key doesn't change baseline, and I don't think we need to block on BCD resolution.
> Add missing media query key

- features/screen-capture.yml
- features/screen-capture.yml.dist
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API
> Add screen capture

- features/flexbox.yml
- features/flexbox.yml.dist
- features/font-face.yml
- features/font-face.yml.dist
- features/text-emphasis.yml
- features/text-emphasis.yml.dist
No changes to baseline. These keys weren't getting picked up by the drafts script.
> Add missing flexbox, font-face and text-emphasis keys

- docs/baseline.md
Today, the web-features owners group met for our quarterly governance call. We reviewed the definition and decided to make no changes today and bring the definition up for review again next year.
That said, we acknowledge that work at the end of this year and the beginning of next (such as dealing with discouraged features) might lead to changes to the Baseline definition sooner. In any case, we'll revisit the definition in about six months.
(We agreed on the call to this date change, so I wasn't planning to request reviews from the entire owners group.)
> Advance review date on the Baseline definition

- scripts/stats.ts
This adds a few things to the `stats` script:
- a `compatKeysUnmapped` count
- a `currentBurndownSize` count (standard, non-deprecated keys to go)
- a `--verbose` flag, to get the list of `currentBurndown` keys
- an export, so I can use this script's output to generate part of the releases (to come later)
If you want only the burndown list, then `npx tsx ./scripts/stats.ts --verbose | jq --raw-output '.currentBurndown[]'` pretty prints it (that probably deserves an entry in `npm run`, honestly).
Built atop #2211.
> Report unmapped non-deprecated, standard keys

- features/meta.yml
- features/meta.yml.dist
- features/table.yml
- features/table.yml.dist
- features/text-tracks.yml
A few such keys remain in drafts, that I expect to be taken care of in https://github.com/web-platform-dx/web-features/pull/2044.
> Uncomment keys excluded for non-real values, now fixed

- features/promise.yml
- features/promise.yml.dist
Adds
- javascript.builtins.Promise.@@species
- javascript.builtins.Promise.incumbent_settings_object_tracking
to the Promise feature and also adds `compute_from` (which wasn't around when I first created this feature)
> Add more keys to Promise

- features/shared-memory.yml
- features/shared-memory.yml.dist
Adds javascript.builtins.Atomics.Atomic_operations_on_non_shared_buffers to the feature. I don't think this is important enough to deserve its own feature so I think it should be sorted in here.
> Add a key to SharedArrayBuffer and Atomics

- features/selection-api.yml
- features/selection-api.yml.dist
All the other keys in #1380 have been assigned to features. This is the last one from that PR.
Closes https://github.com/web-platform-dx/web-features/pull/1380
> Add key to `selection-api`

- features/details.yml
- features/details.yml.dist
- features/popover.yml
- features/popover.yml.dist
The `toggle` event is much older than popovers, we just hadn't captured that previously as it was before we had the option of `compute_from`.
See https://github.com/web-platform-dx/web-features/pull/2284#discussion_r1850288672.
> Move `toggle` event from `popover` to `details`

- features/lab.yml
- features/lab.yml.dist
- features/oklab.yml
- features/oklab.yml.dist
These were excluded because compute_from didn't yet exist. There's an argument to be made that these should be considered baseline in August instead of May, when mixed type parameters were added, and the compute_from should be excluded, but I could be convinced either way.
> Add mixed type parameters to lab/lch, oklab/oklch

- gh-pages/src/web-features.md
"an entire JavaScript APIs" doesn't work because it simultaneously requires singularity and plurality.  
Since the sentence begins with a very small feature consisting of a singular property and a singular technology and works its way up to a vast feature consisting of some of everything, I'm guessing that the API is meant to be singular—giving two more simple examples before jumping to the complex example.
> fix grammar conflict in web-features.md

- features/button.yml
- features/input-button.yml
- features/input-checkbox.yml
- features/input-color.yml
- features/input-date-time.yml
- features/input-file.yml
- features/input-hidden.yml
- features/input-image.yml
- features/input-number.yml
- features/input-password.yml
- features/input-radio.yml
- features/input-range.yml
- features/input-reset.yml
- features/input-submit.yml
- features/input.yml
- features/search-input-type.yml
I think these are complete now. I went and read through all of them, then revised them as a group.
> Revise `<input>` type descriptions

- features/vertical-form-controls.yml
- features/vertical-form-controls.yml.dist
This adds using `direction` to change slider direction. 
Firefox and Safari only have partial support per https://github.com/mdn/content/pull/32142#issuecomment-1961833182. I checked and that still is the case. I chose to `compute_from: writing-mode.vertical_oriented_form_controls` but alternatively we could move the feature to `baseline: false`.
> Add direction to vertical form controls

- docs/baseline.md
https://github.com/web-platform-dx/web-features/issues/2133 prompted me to add two non-normative notes to the Baseline definition, explicitly highlighting some (IMO, intentionally) undefined qualities of the definition.
> Baseline defintion: flag undefined status situations

- features/gradients.yml
- features/gradients.yml.dist
- features/inherit-value.yml
- features/inherit-value.yml.dist
Adds `css.types.image` to `gradient`, and `css.types.global_keywords` to `inherit`. No changes in baseline. A good candidate for #1173.
> Add root types where they were first used

- features/ambient-light.yml
- features/ambient-light.yml.dist
- features/draft/spec/ambient-light.yml
https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor
> Add Ambient light sensor

- features/fullscreen.yml
- features/fullscreen.yml.dist
Added a compute_from to ignore `css.selectors.fullscreen.all_elements`, and remove a now-deprecated key.
> Clean up fullscreen todo comments

- features/iframe-sandbox.yml
- features/iframe-sandbox.yml.dist
I removed a few "Part of XYZ keys". We will get to them when we deal with these APIs as separate features.
> Move sandboxed iframes out of draft

- .github/workflows/gh-pages-build-deploy.yml
This will still go through the motions of building a deployment, but it won't actually try to deploy.
This was prompted by failed deploys on my fork, sending me notification emails.
> Skip GitHub Pages deployment, if GitHub Pages isn't turned on

- features/server-timing.yml
- features/server-timing.yml.dist
`http.headers.Server-Timing.trailer` comes from https://github.com/mdn/browser-compat-data/pull/25141.
Added a `compute_from` as a consequence.
> Add a key to server-timing

- features/not.yml
Other functional pseudo-classes show the parentheses.
> Rename `:not` to `:not()` for consistency

- features/active-view-transition.yml
Pseudo-classes only have one colon.
> Fix incorrect syntax in active-view-transition.yml

- docs/publishing.md
Spotted some typos in `docs/publishing.md`, sending in a fix & other changes from formatting.
> docs: fix some typos in publishing doc

- features/container-queries.yml
- features/container-style-queries.yml
- groups/container-queries.yml
Fixes #2249.
@captainbrosset Since you added the original groups, I thought I'd flag you to verify this makes sense to you. Container queries create containment somewhat as a side effect, but since that's not the point of using them, I put the new `container-queries` group under CSS instead of containment. Does that make sense to you?
> Update container query specs

- features/http3.yml
Since HTTP/3 has no representation in BCD, the following version numbers are from https://caniuse.com/http3.
Closes #2369
> Update http3 for Safari support

- .github/workflows/publish_next_web-features.yml
Removes softprops/action-gh-release in favor of the `gh` CLI.
Fixes https://github.com/web-platform-dx/web-features/issues/2068
Closes https://github.com/web-platform-dx/web-features/pull/2425
> Auto-advance date of the `next` tag

- .github/workflows/publish_next_web-features.yml
I think this fixes https://github.com/web-platform-dx/web-features/issues/2068 again and supersedes https://github.com/web-platform-dx/web-features/pull/2453.
This version does these steps:
- Sets the existing pre-release to draft
- Advances the release tag
- Edits the existing pre-release with the latest details and publishes it again
On my fork, this prevented the notifications that @szepeviktor reported.
> Update prerelease without creating needless notifications

- features/events.yml
This is one of those foundational features that's both difficult to avoid and hard to make explicit inside our length constraints.
Fixes https://github.com/web-platform-dx/web-features/issues/2413, I hope.
> Revise `event` description to make it clear that it's generic

- docs/publishing.md
Setting via the UI is a little bit of a chore.
Learned via https://jvns.ca/til/setting-secrets-with-the-github-cli-is-great/
> Publishing docs: document CLI usage for setting a repository secret

- index.ts
This accidentally slipped in when I was trying to figure out why a previous PR was producing unexpected test results ([original PR](https://github.com/web-platform-dx/web-features/pull/2388/files#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122)).
> Remove left-over debugging log message

- features/cap.yml
- features/ic.yml
- features/lh.yml
This is the style of the other units, like `ch`.
> Make CSS length unit descriptions consistent

- features/wasm-string-builtins.yml
- features/wasm-string-builtins.yml.dist
These keys are tagged as part of the feature in BCD, but not here.
> `wasm-string-builtins`: add keys tagged in BCD

- gh-pages/src/baseline-in-the-wild.md
- gh-pages/src/use-baseline.md
I saw a missing word when reading the gh-pages and added RUMvision to **in the wild** section
> Gh pages adding rumvision

- eslint.config.js
- packages/compute-baseline/src/browser-compat-data/feature.test.ts
- scripts/caniuse.ts
- scripts/release.ts
This enables an eslint rule to prevent unused variables everywhere, cementing a suggestion from @Elchi3 in https://github.com/web-platform-dx/web-features/pull/2544#discussion_r1923807759.
> Disallow unused variables

- features/svg-discouraged.yml
- features/svg-discouraged.yml.dist
https://github.com/web-platform-dx/web-features/commit/2837806aaa04ae1b16074a0863e4ea4916382bf7 is the interesting commit.
(I can undo the sorting if needed. I guess it doesn't really matter since the list is getting removed at a later stage)
> Add SVG <cursor> and SVG <tref> to discouraged SVG feature

- docs/publishing.md
- packages/web-features/README.md
A couple of weeks ago, it came up on the WebDX call that we should have a dedicated announcements channel for web-features consumers. This is my proposal for doing that.
This PR adds documentation describing a process for publishing project announcements to GitHub Discussions.
If we choose to merge this PR, then we'll need to do the following just before merging:
After merging, we should:
> Use GitHub Discussions for periodic announcements

- features/shadow-dom.yml
- features/shadow-dom.yml.dist
This adds keys in a similar style as https://github.com/web-platform-dx/web-features/pull/2596, but for `attachShadow()`.
> Add more keys to `shadow-dom`

- scripts/dist.ts
This was a bug in a somewhat complex set of conditionals.
This also removes the warnings about deprecated keys, since we allow them in certain settings.
Helps along https://github.com/web-platform-dx/web-features/pull/2643
> Allow discouraged features to use `compute_from`

- features/anchor-positioning.yml
- features/anchor-positioning.yml.dist
- features/popover.yml
- features/popover.yml.dist
This adds some new popover keys, one set for creating implicit anchor positioning references and the other that creates an API for comparable to the declarative `popovertarget`.
See also:
- https://chromestatus.com/feature/5120638407409664
- https://github.com/whatwg/html/pull/10728
> Add new popover-related keys

- docs/CONTRIBUTING.md
- features/overflow-overlay.yml
- features/text-decoration-line-blink.yml
- features/word-break-break-word.yml
Fixes #2678.
There are only a few features which names use backtick characters for code. The vast majority of the features only use plain text for the `name` field.
This PR removes the backtick markdown tagging from the feature names.
> Remove backtick markdown tagging from feature names

- features/symbol.yml
- features/symbol.yml.dist
I'll admit it: this is a bit of a hack.
Like other `species` keys, this key properly belongs in the `array` feature. But it we can't put it there just yet.
Because we added the array features early, it's broken down much more finely than other JavaScript collections (and lot of it ought to be combined, when we've dealt with https://github.com/web-platform-dx/web-features/issues/91). That means this key doesn't fit into very neatly into `array` or any of the other existing array features.
But it also doesn't make sense as a standalone feature. It's really hard to describe [an iffy contrivance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species#using_species) as a "feature." I'm not even sure what the pitch is, exactly ("You can make a subclass …
> Add `Array[Symbol.species]` to `symbol`

- features/cookie-store.yml
- features/cookie-store.yml.dist
BCD added a lot of new detail to this API.
https://github.com/mdn/browser-compat-data/pull/25894
> `cookie-store`: add new keys

- features/ua-client-hints.yml
- features/ua-client-hints.yml.dist
https://github.com/mdn/browser-compat-data/pull/25949 added these keys upstream.
I don't know if it's worth the trouble of a `compute_from` for a single-implementation feature. So I didn't bother. I don't know if that's a good call or important in this case.
> `ua-client-hints`: add new keys

- features/media-session.yml
- features/media-session.yml.dist
I thought this looked similar enough to `setCameraActive` and `setMicrophoneActive` to let it stay with its siblings.
> Add new `setScreenshareActive` key to `media-session`

- features/base64encodedecode.yml
- features/base64encodedecode.yml.dist
- features/canvas-2d.yml
- features/canvas-2d.yml.dist
- features/setinterval.yml
- features/setinterval.yml.dist
- features/settimeout.yml
- features/settimeout.yml.dist
Most of these don't make much of a difference, but `features/base64encodedecode.yml` shifts the Baseline date by 13 months. We could do a `compute_from` on that one, if desired.
> Assign `worker_support` keys

- features/date-to-gmt-string.yml
- features/escape-unescape.yml
- features/reporting.yml
> Fix more typos

- features/accesskey.yml
- features/autocapitalize.yml
- features/autocorrect.yml
- features/autofocus.yml
- features/contenteditable.yml
- features/enterkeyhint.yml
- features/inert.yml
- features/lang-attr.yml
- features/spellcheck.yml
- features/translate.yml
This fixes #2748 by making most HTML attributes (and global attributes) lowercase and only contain the attribute name. This is similar to CSS property features, where the name of the features is just the property name itself, all lowercase.
There are exceptions to this, notably Popover which is an attribute and an API. So I kept Popover (capitalized).
> Make HTML attribute names lowercase.

- features/numeric-factory-functions.yml
- features/numeric-factory-functions.yml.dist
New units keep being added to the platform, but it's not reasonable for
this feature to keep changing in response.
Note that the versions now match CSS Typed OM exactly, which makes sense
since this is really part of that feature.
> Pin CSS numeric factory functions to the earliest ones

- packages/compute-baseline/package.json
#2824 bumped the peer dependency for @mdn/browser-compat-data to ^6.0.0. https://github.com/openwebdocs/web-docs-backlog/actions/runs/14171284132/job/39695462685 failed because of a conflicting peer dependency in compute-baseline.
Doing this as in #2764, though I'm unsure if this should be 0.4.0 or 0.3.1
> Increment compute-baseline version to 0.3.1

- gh-pages/src/baseline-in-the-wild.md
The `require-baseline` eslint/css rule was renamed to `use-baseline`. And when I went to fix that I found out that the link to edit this doc was also broken 😄
> Fix a couple of broken links on baseline-in-the-wild.md

- features/beforeinstallprompt.yml
It is supported in Chromium, but nowhere else.
> Remove incorrect "not" in beforeinstallprompt comment

- features/beforeunload.yml
Such as beforeinstallprompt, hashchange, and messageerror.
> Make beforeunload name consistent with other event features

- features/accesskey.yml
The canonical case of the attribute is `accesskey`. The reflected
property (aka IDL attribute) is `accessKey`, but that's not what the
feature is named after.
> Fix capitalization of accesskey attribute in description

- gh-pages/src/baseline-in-the-wild.md
Using the Web Platform API, I built an MCP server to ask for the Baseline status.
https://github.com/yamanoku/baseline-mcp-server
> add: Baseline MCP Server

- features/video.yml
- features/video.yml.dist
This is the type of HTMLMediaElement's error property, and an orignal
(or almost) part of the API. The message property was a later
improvement, but still very Baseline by now.
> Add MediaError to <video>

- features/messageerror.yml
- features/messageerror.yml.dist
- features/service-workers.yml
- features/service-workers.yml.dist
The event on ServiceWorkerContainer and ServiceWorkerGlobalScope should
be given the same treatment for consistency. messageerror shipped after
service workers in all features in all browsers, so this seems like the
right move, rather than letting the service worker feature have both.
The moved event isn't Baseline, so again for consistency exclude both
from the compute_from list. This changes some browser versions to be
earlier, but doesn't change the Baseline date, determined by Safari.
> Move service worker event to the messageerror feature

- features/document-caretpositionfrompoint.yml
- features/document-caretpositionfrompoint.yml.dist
This is a new addition. Pin the feature to just the entry point. This
changes the Firefox version to 20 instead of 23, and getClientRect() is
the bit that previously pushed it to 23. This seems OK as it's in the
distant past and doesn't change the Baseline dates.
> Add option param to caretPositionFromPoint() feature

- features/execcommand.yml
- features/execcommand.yml.dist
execCommand() is supported everywhere, it's just discouraged.
> Fix `execCommand()` browser support status (still not Baseline)

- packages/web-features/README.md
The current `web-features` README says to not show version numbers when using our data. This is too strongly worded (and placed in a confusing spot). This adds some new text to ask consumers to contextualize version numbers.
Fixes https://github.com/web-platform-dx/web-features/issues/2498
> Improve README browser version display guidance

- features/title-attr.yml
This closes the loop on whether `title` is broadly or narrowly discouraged.
Fixes https://github.com/web-platform-dx/web-features/issues/2461
> Note `title` feature's non-discouragement

- features/time-relative-selectors.yml
https://w3c.github.io/webvtt/#the-past-and-future-pseudo-classes is the better spec link for this, as it defines when these pseudo-classes match.
Use the same order as the spec does, because it makes sense.
Also spell out that this is for text track cues.
> Update spec link and description of :past and :future

- features/web-animations.yml
- features/web-animations.yml.dist
This PR makes some adjustments to the `web-animations` feature, to more closely align with caniuse and respond to feedback given in #2244.
Specifically, I've made the following changes:
- Pinned the feature's status to a broader part of the API, including `getAnimations()`, the `Animation()` constructor, and some common controls
- Changed the description to a capture the whole utility of programmatic animation, instead of fitting specifically to the `animate()` attribute
The main consequence here is to shift the Baseline low date forward by about 6 months, though still within the same calendar year.
Fixes https://github.com/web-platform-dx/web-features/issues/2244
Closes https://github.com/web-platform-dx/web-features/pull/2251/
> Update `web-animations` pinned keys and description

- features/fetch-priority.yml
Canonical case for HTML attributes is lowercase.
> Fix capitalization of fetchpriority HTML attribute

- features/display-ruby.yml
- features/display-ruby.yml.dist
- features/ruby-position.yml
- features/ruby-position.yml.dist
Fixes https://github.com/web-platform-dx/web-features/issues/2634, mostly based on a subject matter expert's commentary given in https://github.com/web-platform-dx/web-features/issues/2634#issuecomment-2660850912.
This PR makes two changes to the feature definitions for ruby annotations:
- Moves `css.properties.ruby-position.alternate` to `display-ruby`, under the understanding that the behavior is only meaningful in the context of multi-level ruby, which is represented by the `display: ruby-text-container` declaration.
This affects the reported version numbers for support, but since it's a limited-availability feature anyway I thought it was better to group the closely-related keys.
- Explicitly pin `ruby-position` to the `over` and `under` values.
A note on something I did **not** do: …
> Refine `ruby-position` and `display-ruby` key selection

- features/temporal.yml
- features/temporal.yml.dist
See #3018 for the reason. In short, Firefox 129 does support Temporal, with the exception of 3 BCD keys which are partial. I don't think web-features should block the Firefox support because of these keys.
Fixes #3018.
> Pin Temporal support to top-level object to show Firefox 139 as supported

- .github/workflows/audit_consumers.yml
- package-lock.json
- package.json
- scripts/audit-consumers.ts
web-features IDs are used by other projects, and there's no linting in
place to guarantee that only valid IDs are used. Invalid IDs can appear
becaues of typos, changes to web-features, or because an ID is used
speculatively with the expectation it will be added to web-features.
By reporting on the use of unknown IDs, we can catch these problems. If
it becomes too common we might consider some form of linting in the
monitored projects, but for now this is a lightweight approach that
allows for maximum flexibility early in the lifecycle of a feature.
> Add script to find unknown web-features IDs for triage

- docs/baseline.md
Fixes #502. The document used a mix of "governance group" and "owners group" to refer to the owners group. To avoid any confusion, this update uses "owners group" everywhere.
(This updates the Baseline definition document, but I'd say that it does not technically change the definition itself!)
> Use "owners group" consistently

- packages/compute-baseline/README.md
It looks like `computeBaseline()` expects `checkAncestors`, not `withAncestors`.
> Update compute-baseline README: withAncestors to checkAncestors

- groups/webassembly.yml
See https://webassembly.org/: WebAssembly (abbreviated Wasm) is a binary instruction format [...]
> Fix typo: WASM -> Wasm

- .github/dependabot.yml
Without this change, Dependabot only updates `package-lock.json` in some cases. See https://github.com/web-platform-dx/web-features/pull/3127/ for an example.
This was previously configured (https://github.com/web-platform-dx/web-features/commit/6ac2ef2325d26b0c430c6dd08665d2361fa4653d) but my recent changes (https://github.com/web-platform-dx/web-features/pull/3118) failed to include this detail.
While I'm here, I removed some spurious group filtering rules that I thought constrained the types of upgrades applied, not which group they appeared in.
> Let Dependabot update all `package.json` files

- .github/workflows/audit_consumers.yml
- scripts/audit-consumers.ts
Also handle errors so that the workflow fails instead of continuing to file an empty report.
> Pass GitHub token to audit consumers script

- features/createimagebitmap.yml
https://github.com/web-platform-dx/web-features/pull/3165 broke our feature from caniuse's definition; we shouldn't claim equivalence (or allow the Baseline banner to appear there).
Related issues:
- https://github.com/web-platform-dx/web-features/issues/3139
- https://github.com/web-platform-dx/web-features/pull/3140
> Unlink `createimagebitmap` feature from caniuse

- features/scroll-snap-events.yml
- features/scroll-snap-events.yml.dist
The SnapEvent constructor itself is missing, but event constructors have
little practical use, so this shouldn't affect the status.
> Pin scroll snap events status to the events themselves

- index.ts
This is table setting for https://github.com/web-platform-dx/web-features/issues/2666 and https://github.com/web-platform-dx/web-features/issues/2339 and https://github.com/web-platform-dx/web-features/issues/2341.
Before this, it was possible to have a draft feature shadow the ID of a published feature. This change improves the safety of moving features from draft to published (and vice versa).
While we don't have draft groups or snapshots, I checked these too since it seemed weird and incomplete not too.
> Require IDs to be unique (even with drafts)

- features/media-capabilities.yml
- features/media-capabilities.yml.dist
- features/media-capture.yml
- features/media-capture.yml.dist
These aren't part of the same API. They're defined here:
https://w3c.github.io/mediacapture-main/#dom-inputdeviceinfo-getcapabilities
https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-getcapabilities
Removing the compute_from here to match the feature description makes
the Baseline year change from 2020 to 20222, but this seems OK.
> Move two getCapabilities() methods out of media capabilities

- features/performance.yml
- features/performance.yml.dist
- features/resource-timing.yml
- features/resource-timing.yml.dist
These bits on performance influence the number of
PerformanceResourceTiming objects stored, and belong with the resource
timing feature. They're defined here:
https://w3c.github.io/resource-timing/#sec-extensions-performance-interface
> Move 3 members of Performance to resource timing

- features/performance.yml
As luck would have it, there was a perfect place to slot it in. The
previous description didn't make sense, because `performance` and
`Performance` are the same thing, one is the instance and one is the
interface.
> Mention PerformanceObserver API in performance feature description

- features/ambient-light.yml
- features/compression-streams.yml
- features/cookie-store.yml
- features/dom-geometry.yml
- features/sanitizer.yml
- features/webdriver.yml
In most places API is more natural and consistent with the rest of
web-features.
Sanitizer is aligned with the wording in parse-html-unsafe.yml.
For WebDriver "interface" isn't wrong, but protocol seems clearer.
> Replace many uses of the word "interface"

- features/move-before.yml
- features/move-before.yml.dist
- scripts/specs.ts
Spec changes were landed here:
https://github.com/whatwg/dom/pull/1307
https://github.com/whatwg/html/pull/10657
> Update moveBefore() spec and BCD keys

- features/region-capture.yml
These are changes suggested by @eladalon1983 after I asked about the current description, which I thought seemed wrong in parts.
> Improve description of region capture API

- package-lock.json
- package.json
- packages/compute-baseline/package.json
- packages/compute-baseline/src/browser-compat-data/feature.ts
- packages/compute-baseline/src/browser-compat-data/index.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.test.ts
- packages/compute-baseline/src/browser-compat-data/supportStatements.ts
- scripts/find-troublesome-ancestors.ts
This upgrades `compute-baseline` (and the project generally) to use `@mdn/browser-compat-data@7.0.0`. Since v7.0.0 does not contain any data changes over v6.1.5, this has no impact on the data, as expected.
This causes the following breaking changes (maybe use this text when making a release):
- The `RealSupportStatement` class has been removed. All BCD statements now have "real" values (that is, they do not contain `true` or `null` values where version strings might appear), so the distinction between "real" and "non-real" statements no longer has any meaning. Use the `SupportStatement` class instead.
- The `statement()` factory function has been removed. It serves no purpose without the real/non-real value distinction. Use `new SupportStatement()` instead.
> Upgrade `compute-baseline` to use BCD 7.0.0

- features/field-sizing.yml
The `fied-sizing` property has been moved to the CSS Form Control Styling level 1 module.
> Update the spec URL for field-sizing

- features/notifications-apps.yml
Progress on #3417
In the Matrix chat @captainbrosset said:
> Ah, I think you're right, that we should just change "low" to "high" in this feature.
> It would have been good to break the build here. I thought we had sanity checks for these kinds of things.
> I actually came across a test just yesterday that, I think, is supposed to check for dates and baseline stages ...
> But I'll need @ddbeck to investigate more deeply here
This PR addresses the immediate issue of manually updating the feature's status to "high" but there's still some investigation needed into why it didn't get flagged sooner.
> Change notifications-apps Baseline status to high
