web-platform-dx/web-features

feature-group-definitions/README.md
This seeds a directory for bringing the work of work of [ddbeck/common-web-platform-feature](https://github.com/ddbeck/common-web-feature-mockup/) over here.
This week, Chris (I don't know his GitHub username, unfortunately) posed an interesting question to the WebDX CG call, which was, badly paraphrased: **what is a web feature?** Coincidentally, I was also wondering about this question myself a few weeks previous and had written myself an answer. I didn't think anyone would be interested in it, but since Chris asked, I've tidied it up and used it to start the README for the feature grouping work.
cc: @atopal
=> Add starter file for feature grouping effort

.github/dependabot.yml, .github/workflows/build.yml, .gitignore, build.ts, feature-group-definitions/subgrid.yml, package-lock.json, package.json
That feature is Subgrid, with a spec link.
The package is in the root directory even though feature-group-definitions/ would make sense, as this simplifies Dependabot and GitHub Actions setup.
=> Start a web-features package consisting of 1 feature

feature-group-definitions/cascade-layers.yml, feature-group-definitions/dialog.yml, feature-group-definitions/flexbox.yml, feature-group-definitions/fullscreen.yml, feature-group-definitions/idle-detection.yml, feature-group-definitions/temporal.yml, feature-group-definitions/webcodecs.yml, feature-group-definitions/webvtt.yml
=> Add 8 more features and their spec URLs

.github/workflows/pull_request.yml, index.ts, package-lock.json, package.json, scripts/specs.ts
Closes https://github.com/web-platform-dx/feature-set/issues/12.
=> Check feature spec URL against web-specs

feature-group-definitions/popover.yml
Added to HTML here:
https://github.com/whatwg/html/pull/8221
https://github.com/whatwg/html/pull/8717
=> Add popover feature

packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-bbxNBo/index.released.pretty.json	2023-03-27 19:34:52.000000000 +0200
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-bbxNBo/index.prepared.pretty.json	2023-03-27 19:34:55.000000000 +0200
@@ -114,7 +114,8 @@
"usage_stats": "https://chromestatus.com/metrics/feature/timeline/popularity/1624"
},
"popover": {
-    "spec": "https://html.spec.whatwg.org/multipage/#the-popover-attribute"
+    "spec": "https://html.spec.whatwg.org/multipage/#the-popover-attribute",
+    "usage_stats": "https://chromestatus.com/metrics/feature/timeline/popularity/4191"
},
"sanitizer": {
"spec": "https://wicg.github.io/sanitizer-api/"
```
=> 📦 Release web-features@0.2.1

feature-group-definitions/subgrid.yml
This one is pretty straightforward: not baseline yet.
=> Add baseline status to `subgrid`

packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-zQxaGs/index.released.pretty.json	2023-04-20 16:06:51.000000000 +0200
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-zQxaGs/index.prepared.pretty.json	2023-04-20 16:06:54.000000000 +0200
@@ -2,9 +2,87 @@
"anchor-positioning": {
"spec": "https://drafts.csswg.org/css-anchor-position-1/#anchoring"
},
+  "array-at": {
+    "compat_features": [
+      "javascript.builtins.Array.at"
+    ],
+    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at"
+  },
+  "array-flat": {
+    "caniuse": "array-flat",
+    "compat_features": [
+      "javascript.builtins.Array.flat",
+ …
```
=> 📦 Release web-features@0.3.0

feature-group-definitions/fetch-priority.yml
The feature is both the support in Fetch and the HTML attributes.
A BCD entry for the Request parameter is missing.
=> Add Fetch Priority feature

feature-group-definitions/canvas-context-lost.yml, feature-group-definitions/cascade-layers.yml, feature-group-definitions/container-queries.yml
I've gotten a bit better at (manually) exercising the baseline status, so I went through everything we already had to make sure it was correct. Some changes fell out of that. I'll self-review with detailed commentary.
=> Update baseline statuses

feature-group-definitions/grid-animation.yml, feature-group-definitions/grid.yml
This adds Baseline status for `grid`. I'll self-review with some implementation notes.
=> Add Baseline status to `grid` (and add `grid-animation`)

packages/web-features/package-lock.json, packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-qslywr/index.released.pretty.json	2023-05-05 16:31:18.000000000 +0200
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-qslywr/index.prepared.pretty.json	2023-05-05 16:31:20.000000000 +0200
@@ -85,7 +85,30 @@
},
"border-image": {
"caniuse": "border-image",
+    "compat_features": [
+      "css.properties.border-image",
+      "css.properties.border-image.fill",
+      "css.properties.border-image.gradient",
+      "css.properties.border-image.optional_border_image_slice",
+      "css.properties.border-image-outset",
+      "css.properties.border-image-repeat",
+      "css.properties.border-image-repeat.round",
+ …
```
=> 📦 Release web-features@0.4.0

README.md
Since we're anticipating more activity here soon, I've taken a shot at improving the README, with contributors as a major audience (and using this opportunity to [eat my own dog food](https://github.com/ddbeck/readme-checklist)).
=> Revise README for Baseline launch

packages/web-features/package-lock.json, packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-GxUVgR/index.released.pretty.json	2023-05-09 19:15:12.000000000 +0200
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-GxUVgR/index.prepared.pretty.json	2023-05-09 19:15:14.000000000 +0200
@@ -457,15 +457,6 @@
"api.OffscreenCanvasRenderingContext2D.translate"
],
"spec": "https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface",
-    "status": {
-      "is_baseline": false,
-      "support": {
-        "chrome": "80",
-        "edge": "80",
-        "firefox": "105",
-        "safari": "16.4"
-      }
-    },
"usage_stats": "https://chromestatus.com/metrics/feature/timeline/popularity/1624"
}, …
```
=> 📦 Release web-features@0.4.1

packages/web-features/README.md
=> Fix typo in README

feature-group-definitions/view-transitions.yml
- Is this a reasonable spec link for the feature? Is it a reasonable caniuse reference?
=> Add View Transitions feature

docs/CONTRIBUTING.md
These are the last instances of `feature-set` in the repo.
=> Rename `feature-set` to `web-features` in one more place

feature-group-definitions/web-animations.yml
This a new feature proposal for the Web Animations API.
It corresponds to https://caniuse.com/web-animation
=> Add web animations api feature

feature-group-definitions/where.yml
This goes well with https://github.com/web-platform-dx/web-features/pull/308.
=> Add `:where()` pseudo-class feature

feature-group-definitions/subgrid.yml
make subgrid baseline
https://caniuse.com/css-subgrid
=> Subgrid is now baseline

GOVERNANCE.md
On Tuesday, 7 November 2023, the governance team decided to invite Philip to the owners group, as a core contributor.
@foolip could you confirm that you accept the invitation? Thank you!
Related: https://github.com/web-platform-dx/web-features/pull/416
=> Add @foolip as an owner

GOVERNANCE.md
On Tuesday, 7 November 2023, the governance team decided to invite James to the owners group.
@jgraham could you confirm that you accept the invitation? Thank you!
=> Add @jgraham as an owner

feature-group-definitions/custom-properties.yml
- Are listed features plausible pieces of the feature as a whole?
=> `custom-properties`: add compat features

feature-group-definitions/webtransport.yml
- Are listed features plausible pieces of the feature as a whole?
=> `webtransport`: add compat features

.prettierignore, package.json, scripts/feature-init.ts
This script makes it slightly easier to get a new feature started, by creating a file in the right directory and seeding it with usual fields.
=> Add `feature-init` script

feature-group-definitions/has.yml
This was just added:
https://chromium-review.googlesource.com/c/chromium/src/+/5040015
=> Link Chrome use counter for :has()

feature-group-definitions/webvtt.yml
Part of https://github.com/web-platform-dx/web-features/issues/447.
=> Link only one use counter for WebVTT

packages/web-features/README.md
=> Fix typo on the package README.md

packages/web-features/package-lock.json, packages/web-features/package.json, scripts/release.ts
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-CbYFN1/index.released.pretty.json	2023-12-04 17:31:37.000000000 +0100
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-CbYFN1/index.prepared.pretty.json	2023-12-04 17:31:39.000000000 +0100
@@ -6,7 +6,20 @@
"compat_features": [
"javascript.builtins.Array.at"
],
-    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at"
+    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at",
+    "status": {
+      "baseline": "low",
+      "baseline_low_date": "2022-03-15",
+      "support": {
+        "chrome": "92",
+        "chrome_android": "92",
+ …
```
=> 📦 Release web-features@0.5.0-alpha.1

scripts/release.ts
I was troubleshooting some issues with the release scripting in #475  and accidentally merged a change to the release script. This reverts the change.
=> Revert script changes from #475

feature-group-definitions/default.yml, feature-group-definitions/dialog.yml
| Key                                                                                                                                     | Baseline | Low since date | Versions                                                                                                                    |
| :-------------------------------------------------------------------------------------------------------------------------------------- | :------: | :------------- | --------------------------------------------------------------------------------------------------------------------------- |
| **dialog**                                                                                                                              |  🆕 Low  | 2022-03-14     | Chrome 37<br>Chrome Android 37<br>Edge …
=> `dialog`: set Baseline status

feature-group-definitions/tabindex.yml, feature-group-definitions/text-indent.yml
| Key                                                                                                                               | Baseline | Low since date | Versions                                                                                                               |
| :-------------------------------------------------------------------------------------------------------------------------------- | :------: | :------------- | ---------------------------------------------------------------------------------------------------------------------- |
| **tabindex**                                                                                                                      |  ✅ High  | 2018-10-02     | Chrome 1<br>Chrome Android 18<br>Edge 18 🔑💎<br>Firefox 1.5<br>Firefox …
=> Features starting with T: Set Baseline status

feature-group-definitions/flexbox.yml
See https://github.com/mdn/browser-compat-data/pull/21598#issuecomment-1856104041 for the origin of this.
Synchronizes with https://github.com/mdn/browser-compat-data/pull/21610
=> `flexbox`: add missing features

feature-group-definitions/flexbox-gap.yml
Corresponding to https://github.com/mdn/browser-compat-data/pull/21598
=> `flexbox-gap`: create group

packages/web-features/package-lock.json, packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-p5p7gP/index.released.pretty.json	2023-12-18 17:48:36.418101236 +0100
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-p5p7gP/index.prepared.pretty.json	2023-12-18 17:48:38.386030027 +0100
@@ -6,7 +6,20 @@
"compat_features": [
"javascript.builtins.Array.at"
],
-    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at"
+    "spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at",
+    "status": {
+      "baseline": "low",
+      "baseline_low_date": "2022-03-15",
+      "support": {
+        "chrome": "92",
+        "chrome_android": "92",
+ …
```
=> 📦 Release web-features@0.5.0

packages/web-features/package-lock.json, packages/web-features/package.json
```diff
--- /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-HWqfKC/index.released.pretty.json	2024-01-09 16:22:51.000000000 +0100
+++ /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/web-features-HWqfKC/index.prepared.pretty.json	2024-01-09 16:22:53.000000000 +0100
@@ -9,7 +9,7 @@
"spec": "https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.at",
"status": {
"baseline": "low",
-      "baseline_low_date": "2022-03-15",
+      "baseline_low_date": "2022-03-14",
"support": {
"chrome": "92",
"chrome_android": "92",
@@ -260,7 +260,7 @@
"spec": "https://html.spec.whatwg.org/multipage/web-messaging.html#broadcasting-to-other-browsing-contexts",
"status": {
"baseline": "low", …
```
=> 📦 Release web-features@0.5.1

feature-group-definitions/container-queries.yml
This has the same support status as the existing entries.
=> Include container query units in the CQ feature

feature-group-definitions/device-posture.yml
See also https://github.com/mdn/browser-compat-data/pull/21608.
=> Add Device Posture API

feature-group-definitions/picture-in-picture.yml
- Are listed features plausible pieces of the feature as a whole?
=> `picture-in-picture`: add compat features

feature-group-definitions/storage-buckets.yml
Added in https://github.com/mdn/browser-compat-data/pull/21998
=> Add Storage buckets group

feature-group-definitions/media-query-range-syntax.yml
- Are listed features plausible pieces of the feature as a whole?
=> Add feature: `media-query-range-syntax`

feature-group-definitions/jpegxl.yml, scripts/specs.ts
Trust https://caniuse.com/jpegxl for the Safari versions.
=> Add JPEG XL feature

index.ts, package-lock.json, package.json, schemas/defs.schema.json, types.ts
Fixes https://github.com/web-platform-dx/web-features/issues/522.
=> Compute Baseline high date from low date

feature-group-definitions/container-queries.yml
Fixes https://github.com/web-platform-dx/web-features/issues/546.
=> Include CSSContainerRule in container queries but override support data

feature-group-definitions/linear-easing.yml
As suggested by @danielsakhapov.
=> Update linear() description with use case

feature-group-definitions/color-function.yml, feature-group-definitions/relative-color.yml
Support for RCS isn't computed by hand, waiting for the scripts...
=> Add color() and relative color syntax features

index.ts
As suggested by @ddbeck in https://github.com/web-platform-dx/web-features/issues/532#issuecomment-1999483461
=> Ensure description is not too long

feature-group-definitions/scrollbar-color.yml, feature-group-definitions/scrollbar-gutter.yml, feature-group-definitions/scrollbar-width.yml
Closes https://github.com/web-platform-dx/web-features/pull/303.
=> Add scrollbar-* features

feature-group-definitions/promise.yml, feature-group-definitions/promises.yml
This was recently added to guidelines:
https://github.com/web-platform-dx/web-features/pull/689
Fixes https://github.com/web-platform-dx/web-features/pull/699.
=> Qualify promises with (initial support)

feature-group-definitions/anchor-positioning.yml
This PR adds the `caniuse` and `description` fields to the anchor positioning feature.
=> Add anchor positioning caniuse and description fields

feature-group-definitions/set-methods.yml, feature-group-definitions/set.yml
The tour through ECMAScript continues...
=> Add Set feature

feature-group-definitions/promise.yml
See https://github.com/web-platform-dx/web-features/pull/665.
=> Fix Baseline low date of promises

feature-group-definitions/intersection-observer-v2.yml
Match the name ("intersection observer") of the base feature.
=> Update name of IntersectionObserver v2

docs/README.md
I had a look through several recent PRs writing or modifying descriptions. I tried to capture all of the "rules" that had been put in place so far, though perhaps a bit opinionated on my part.
For a fully-rendered version, see https://github.com/ddbeck/web-features/tree/description-guidelines/docs#descriptions.
=> Add initial description guidelines

feature-group-definitions/font-palette-animation.dist.yml, feature-group-definitions/font-palette-animation.yml
See https://github.com/web-platform-dx/web-features/pull/801/files#r1557484343
=> Add a BCD key to font-palette animation

packages/compute-baseline/src/baseline/index.ts, packages/compute-baseline/src/baseline/support.ts, scripts/dist.ts
=> Add verbosity option to dist script and bring your own logging to compute-baseline

feature-group-definitions/container-queries.yml
This adds a few subfeatures that have the same Baseline date as the rest of the feature.
Part of covering Baseline 2023 features.
=> `container-queries`: include more subfeatures

feature-group-definitions/webusb.dist.yml, feature-group-definitions/webusb.yml
It now matches https://caniuse.com/webusb.
=> Fix the Chrome version (61) of WebUSB

.github/dependabot.yml
This is not clearly documented, but should work:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory https://github.com/dependabot/dependabot-core/issues/2178
=> Update packages/ dependencies together

docs/README.md
From https://github.com/web-platform-dx/web-features/pull/810#discussion_r1555726480
=> Add description style guide entries for "device" and "platform"

.github/labeler.yml, .github/workflows/labeler.yml
This PR will fail (since there's no config on the target branch). I tested it on my own fork, however, and it _ought_ to work.
=> Add GitHub Action to label changes to feature definitions

.github/dependabot.yml
Reverts web-platform-dx/web-features#793
=> Revert "Update packages/ dependencies together"

feature-group-definitions/contain-intrinsic-size.yml
As suggested by @vmpstr. Thanks!
=> Improve contain-intrinsic-size description

docs/README.md
from https://github.com/web-platform-dx/web-features/pull/913#discussion_r1572601975
=> Description guideline: when to use global/`window` object references

feature-group-definitions/README.md, feature-group-definitions/mathml.yml, packages/web-features/README.md, towards-features.md
I found these using cspell. Unfortunately, it produces lots of false positives, so I'm not proposing enforcing its results now.
=> Fix various typos

packages/web-features/package-lock.json, packages/web-features/package.json
This is to publish descriptions.
=> Increment patch version to v0.7.0

docs/README.md
Codifies https://github.com/web-platform-dx/web-features/pull/969
=> Description style guide: prefer "declaration" over "property value"

feature-group-definitions/array.yml, feature-group-definitions/promise.yml
This is to match the name naming of Map and Set.
=> Rename array and promise features to singular

feature-group-definitions/compute-pressure.yml, schemas/defs.schema.json, types.ts
Fixes https://github.com/web-platform-dx/web-features/issues/890.
=> Make Baseline status required

packages/web-features/package-lock.json, packages/web-features/package.json
Status is now always available:
https://github.com/web-platform-dx/web-features/pull/899
=> Increment patch version to v0.8.0

packages/web-features/package-lock.json, packages/web-features/package.json
This is mostly to release https://github.com/web-platform-dx/web-features/pull/1045.
=> Increment patch version to v0.8.1

features/anchor-positioning.dist.yml, features/check-visibility.dist.yml, features/check-visibility.yml, features/compute-pressure.dist.yml, features/customized-built-in-elements.dist.yml, features/customized-built-in-elements.yml, features/resource-timing.dist.yml, features/round-mod-rem.dist.yml, package-lock.json, package.json
Simplify source where possible and update dist as needed.
=> Bump @mdn/browser-compat-data from 5.5.29 to 5.5.30

packages/web-features/package-lock.json, packages/web-features/package.json
This is to release the fix for https://github.com/web-platform-dx/web-features/issues/1164.
=> Increment patch version to v0.8.5

features/picture-in-picture.dist.yml, features/picture-in-picture.yml
This doesn't change the computed status.
=> Add disablepictureinpicture attribute to PiP feature

.github/workflows/refresh_dist.yml
I was too aggressive on the find-and-replace in #1225. 🙄
=> Fix find-and-replace error in refresh dist workflow

packages/web-features/README.md, packages/web-features/package-lock.json, packages/web-features/package.json
This is a breaking release due to exposing groups and snapshots. Update
the README to show the new import style.
=> Increment patch version to v0.10.0

features/details-name.yml, features/figure.yml, features/image-maps.yml, features/samp.yml, features/small.yml, features/table.yml, features/var.yml
I did not touch the drafts, since I thought they were generated (also several will have PRs in progress that I didn't want to conflict with).
=> Change newly-added HTML elements to the html-elements group

GOVERNANCE.md
Closes https://github.com/web-platform-dx/web-features/issues/1474.
=> Add @kosamari @petele @tropicadri as peers

features/transferable-arraybuffer.yml, groups/transferable.yml
This group was added speculatively and adding more things to it seems odd. See https://github.com/web-platform-dx/web-features/pull/1507 for comparison.
Closes https://github.com/web-platform-dx/web-features/pull/1507
=> Remove Transferable group

.gitignore, scripts/build.ts
This is to align better with data.json and data.schema.json.
=> Rename extended JSON file to data.extended.json

docs/CONTRIBUTING.md, docs/guidelines.md
Fixes https://github.com/web-platform-dx/web-features/issues/1642
=> Contributing docs: make fields' text formats explicit

packages/web-features/README.md, packages/web-features/index.ts, packages/web-features/package-lock.json, packages/web-features/package.json
This bumps the version number, but also makes some changes to prevent type errors caused by the semver minor changes in https://github.com/web-platform-dx/web-features/pull/1514.
=> Prepare web-features v1.2.0 release

docs/guidelines.md
I don't want to specify every single style consideration myself, especially for very general things like using the serial comma or OKing contractions. Instead, I think we should have a fallback style guide to refer to when we have not otherwise specified. I like the Microsoft style guide quite a lot, so I picked that one. 
Prompted by https://github.com/web-platform-dx/web-features/pull/1619#discussion_r1729028492
=> Contributor docs: suggest a general style reference

.github/labeler.yml
I also sorted the labels in the configuration file.
=> Add labeler for tools and infrastructure PRs

features/promise-try.yml.dist
https://github.com/web-platform-dx/web-features/pull/1657 turned out to be a little stale.
=> Refresh dist to un-break the build

packages/web-features/package-lock.json, packages/web-features/package.json
Diff for changes in the release (as of right now): https://gist.github.com/ddbeck/57cdad030951e1114debaa458cc19ca4
Please review and (if applicable) approve this PR, but don't merge; I'll merge it myself when I'm ready to do the rest of the release checklist.
=> Prepare v1.4.0 release

GOVERNANCE.md
I've been really pleased with Dietrich and James's recent contributions, so I think it's time to grant them merge privileges.
This needs a few owner approvers before merging. I'll bring this up at  the next WebDX meeting.
=> Add @autonome and @jamesnw as peers

packages/web-features/package-lock.json, packages/web-features/package.json
Please review, but don't merge this—I'll merge it myself when I'm ready to complete the rest of the checklist. Thank you!
This is semver major due to:
- https://github.com/web-platform-dx/web-features/pull/1873
- https://github.com/web-platform-dx/web-features/pull/1918
=> Prepare release v2.0.0

gh-pages/src/baseline-in-the-wild.md
Kadir and James gave a greate talk about baseline and web-features at blinkon: https://www.youtube.com/watch?v=pTsMpoXGlqE
This PR adds the talk to the "Baseline in the wild" page.
=> Add BlinkOn presentation to home page

features/ruby-position.yml, features/ruby-position.yml.dist, features/xhr.yml, features/xhr.yml.dist
See https://github.com/web-platform-dx/web-features/pull/1985
=> Add keys introduced by BCD 5.6.7

features/canvas-2d.yml, features/canvas-2d.yml.dist
No Caniuse. Treats same as other sub-parts of Canvas2d, rolling it up into main feature, eg CanvasGradient. I suspect someday we break these kinds of things out as features, but today is not that day.
=> Add CanvasPattern

features/smil-svg-animations.yml, features/smil-svg-animations.yml.dist
Compare to the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/svg-animations.yml
=> Add more keys to SMIL SVG Animations

features/web-midi.yml, features/web-midi.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webmidi.yml
=> Add a key to web-midi

features/web-cryptography.yml, features/web-cryptography.yml.dist
Compare with the draft file at: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webcryptoapi.yml
(I also sorted keys alphabetically)
=> Add more keys to Web Crypto

features/shared-storage.yml, features/shared-storage.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/shared-storage.yml
=> Add a key to Shared Storage

features/storage-access.yml, features/storage-access.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/storage-access.yml
=> Add more keys to Storage access

features/scheduler.yml, features/scheduler.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/scheduling-apis.yml
=> Add more keys to Scheduler

features/xhr.yml, features/xhr.yml.dist
Maybe this is the final set :)
(I also sorted the list alphabetically to be more certain about it.)
Review with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/xhr.yml
=> Again more keys for XHR

packages/web-features/package-lock.json, packages/web-features/package.json
It looks like we've only added features in this release so far: https://github.com/web-platform-dx/web-features/compare/v2.0.0...b7b4483cd9d13e175ed2b25cf7c1042a59d81d6a
=> Prepare release v2.1.0

features/webusb.yml, features/webusb.yml.dist
Review with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webusb.yml
=> More keys for WebUSB

features/offline-audio-context.yml, features/offline-audio-context.yml.dist, features/web-audio.yml, features/web-audio.yml.dist
Compare with the lastest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webaudio.yml
=> Add more keys to Audio/OfflineAudioContext

features/url.yml, features/url.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/url.yml
=> Add more keys to URL

features/webgpu.yml, features/webgpu.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webgpu.yml
=> Add more keys to WebGPU

features/webhid.yml, features/webhid.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webhid.yml
=> Add more keys to WebHID

features/websockets.yml, features/websockets.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/websockets.yml
=> Add more keys to WebSockets

features/webauthn.yml, features/webauthn.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webauthn-3.yml
=> Add more keys to Web authentication

features/battery.yml, features/battery.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/battery-status.yml
(I also sorted the keys alphabetically)
=> Add more keys to battery

features/console.yml, features/console.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/console.yml
(I also sorted the keys alphabetically)
=> Add a key to console

features/credential-management.yml, features/credential-management.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/credential-management-1.yml
=> Add a key to Credential Management

features/intl.yml, features/intl.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/ecma-402.yml
=> Add a key to Intl

features/eyedropper.yml, features/eyedropper.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/eyedropper-api.yml
=> Add a key to Eyedropper

features/keyboard-map.yml, features/keyboard-map.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/keyboard-map.yml
=> Add more keys to Keyboard map

features/referrer-policy.yml, features/referrer-policy.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/referrer-policy.yml
=> Add more keys to Referrer Policy

.github/workflows/bcd_upgrade_checklist.yml
A follow up to https://github.com/web-platform-dx/web-features/pull/2073
=> Fix checklist for BCD upgrades workflow (round 2)

.github/workflows/bcd_upgrade_checklist.yml
Apparently the search term needs to be single-quoted.
A follow up to https://github.com/web-platform-dx/web-features/pull/2077.
=> Fix checklist for BCD upgrades workflow (round 3)

features/scroll-driven-animations.yml
This is intended to improve the findability of this feature via its most-visible properties.
Fixes https://github.com/web-platform-dx/web-features/issues/2004.
Fixes https://github.com/web-platform-dx/web-features/issues/2003.
Fixes https://github.com/web-platform-dx/web-features/issues/2002.
=> `scroll-driven-animations`: revise description for search

features/picture-in-picture.yml, features/picture-in-picture.yml.dist
Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/picture-in-picture.yml
We authored this feature before we introduced `compute_from`.  :)
=> Add more keys to PiP and use compute_from

packages/web-features/package-lock.json, packages/web-features/package.json
Release for BCD v5.6.10. https://github.com/web-platform-dx/web-features/compare/v2.2.0...main
=> Prepare release v2.3.0

features/nesting.yml, features/nesting.yml.dist
The new keys are baseline false but don't impact the use of the feature, so I set the status.
=> Add new NestedDeclaration keys

features/shared-storage.yml, features/shared-storage.yml.dist
See new keys in https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/shared-storage.yml
=> Add more keys to shared storage

features/webusb.yml, features/webusb.yml.dist
From the draft feature: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webusb.yml
=> Add a key to WebUSB

features/webxr-device.yml, features/webxr-device.yml.dist
From the draft feature: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webxr.yml
=> Add a key to WebXR

features/web-animations.yml, features/web-animations.yml.dist
See https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/web-animations-2.yml
=> Add a key to Web Animations

features/webauthn.yml, features/webauthn.yml.dist
See the draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webauthn-3.yml
=> Add more keys to WebAuthn

features/dom.yml, features/dom.yml.dist
From https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/webidl.yml
(also sorted keys alphabetically, maybe it would be nice to lint this so we could programmatically manipulate `compat_features` lists in the future)
=> Add DOMException to DOM

scripts/stats.ts
Example output:
```
{
"features": 742,
"compatKeys": 9478,
"compatCoverage": 0.6361073825503356,
"compatKeysPerFeatureMean": 12.773584905660377,
"compatKeysPerFeatureMedian": 4,
"compatKeysPerFeatureMode": 1
}
```
=> Add a script to calculate some simple stats about web-features

features/functions.yml, features/functions.yml.dist
Add javascript.builtins.Function.toString.toString_revision to the "functions" feature and sorts keys alphabetically.
=> Add a key to functions feature

features/map.yml, features/map.yml.dist
Adds javascript.builtins.Map.@@species to the map feature.
=> Add a key to Map

features/set.yml, features/set.yml.dist
Add the `javascript.builtins.Set.@@species` key to the `set` feature.
=> Add a key to set feature

features/class-syntax.yml, features/class-syntax.yml.dist
Public, private, static class fields came in later but I think we could sort them in with classes instead of their own features.
=> Add more keys to classes feature

features/font-loading.yml, features/font-loading.yml.dist
Toward https://github.com/web-platform-dx/web-features/pull/2228#issuecomment-2476726277.
=> Remove discouraged `FontFaceSet()` from `font-loading`

features/flexbox.yml, features/flexbox.yml.dist
The `place-X` properties are shorthands for `align-X` and `justify-X` which are already part of this feature.
=> Adds place shorthand keys to flexbox

gh-pages/src/baseline-in-the-wild.md
This isn't a presentation in the same way as the others, but I think we can add additional sections once there is more content. Thanks @captainbrosset for the recommendation to add this here!
=> Add Winging It Live to Baseline in the wild

scripts/find-ranged-headline-statuses.ts
This came up in the course of https://github.com/web-platform-dx/web-features/pull/2409#pullrequestreview-2488845296 and will probably continue to be useful until we've contributed changes upstream.
=> Add script to find features with ranged (≤) headline statuses

features/indexeddb.yml
=> Fix indexeddb name

features/accelerometer.yml, features/accelerometer.yml.dist, features/magnetometer.yml, features/magnetometer.yml.dist
=> Add missing keys to accelerometer and magnetometer

features/gamepad-haptics.yml, features/gamepad-haptics.yml.dist, features/gamepad-vr.yml, features/gamepad-vr.yml.dist, features/gamepad.yml, features/gamepad.yml.dist
I suspect these were surfaced after initial work on #2434 was started.
=> Add secure context and iframe to Gamepad features

.gitattributes
Currently juicy parts (YAML files) are hidden.
Docs: https://github.com/github-linguist/linguist/blob/main/docs/overrides.md#summary
=> Improve GitHub stats

.github/workflows/bcd_upgrade_checklist.yml, .github/workflows/remove_tagged_compat_features.yml
See https://github.com/web-platform-dx/web-features/issues/1672#issuecomment-2618392903
=> Add a workflow to remove tagged compat features

features/container-scroll-state-queries.yml, features/container-scroll-state-queries.yml.dist
BCD added more detail to this feature.
https://github.com/mdn/browser-compat-data/pull/25941
=> `container-scroll-state-queries`: add new keys

features/print-color-adjust.yml
This is the typical style for features corresponding to a CSS property.
=> Name print-color-adjust feature after property

features/video.yml, features/video.yml.dist
This is the type of video.buffered/played/seekable.
=> Add TimeRanges to `<video>` feature

features/fetch-request-streams.yml
Toward https://github.com/web-platform-dx/web-features/issues/2818
=> Rename "Fetch request streams" to "Fetch upload streams"

gh-pages/src/baseline-in-the-wild.md
Responding to https://github.com/web-platform-dx/web-features/issues/264#issuecomment-3084645323
=> Adds link to browserslist-config-baseline on gh-pages site

features/webgl-compressed-texture-pvrtc.yml.dist, package-lock.json, package.json
This will make it easier to show that the code changes required for v7.0.0 don't create dist file changes.
=> Upgrade to last BCD v6 series release

gh-pages/src/baseline-in-the-wild.md
Addressing the addition in #641
=> Update to include cssdb in the list of dashboard

docs/CONTRIBUTING.md
See https://github.com/web-platform-dx/web-features/issues/3088#issuecomment-3299378003
=> Clarify how to contribute nascent features
